### ISSUE TITLE
Make sure the design works well for nesting server-side GraphQL with client state

### ISSUE THREAD

**Issue by glasser** [apollographql/apollo-link-state#1]
I was just chatting about these ideas with @stubailo and he suggested I file an issue.

I think one of the aspects that makes apollo-link-state potentially more powerful and expressive than other state management solutions like Redux is the ability for server state and client state to nest with each other.  For example, imagine this query for a todo list where items can be selected as part of client-side state:

```
query list {
  list(name: "my list") {
    items {
      name
      isDone
      isSelected @client
    }
  }
}
```

Getting the per-item local state nicely nested inside the server-side state in your component's data prop would be super convenient!

My actionable suggestion is that we build something like this as one of the motivating (and tested) examples for apollo-link-state. (I don't have the time to actually help with this myself, unfortunately.) It doesn't necessarily need to be the main example: @stubailo pointed out that we don't want folks to think that apollo-link-state is *only* useful for cross-source nested data. But we definitely should make sure it's natural and easy to do things like this, in my opinion!

**Comment by jbaxleyiii** [comment]
@glasser @stubailo this is a great sample to have written as a test and documented! It also brings up an interesting question about data resolution in this space.

Given the above query:
```graphql
query list {
  list(name: "my list") {
    items {
      name
      isDone
      isSelected @client
    }
  }
}
```

I would imagine determining the `isSelectedStatus` may need to come from the sibling data. On the server, a resolver like `isDone` would be called with the source data of the fetched items. On the client, something like an `id` would most likely be the link between some level of local saving of data.

I think when applying the resolvers for types, we need to ensure server data is passed at its level to extend server data into calculated values.

This would also give the ability to an idea @evans pitched to me at Summit which would allow the local state link to augment the server schema with virtual fields. For instance:

```graphql
query Me {
  user {
    firstName
    lastName
    fullName @client
  }
}
```

Where `fullName` is a calculated value of `firstName + ' ' + lastName`

**Comment by jbaxleyiii** [comment]
@glasser test added [here](https://github.com/apollographql/apollo-link-state/pull/2/files)

One thing I am concerned about is writing to the cache for sibling client fields as this should ideally be batched into a single write operation. This would be beneficial for updates as well so maybe a `dataProxy` api for batch writes?
