### ISSUE TITLE
where does `client` come from in readme example? 

### ISSUE THREAD

**Issue by barbalex** [apollographql/apollo-link-state#105]
You are using the variable `client` in this example:

```js
const local = withClientState({
  Query: {
    // provide an initial state
    todos: () => [],
  },
  Mutation: {
    // update values in the store on mutations
    addTodo: (_, { message, title }, { cache }) => {
      const current = client.readQuery({ query, variables });
      const data = {
        todos: current.todos.concat([
          { message, title, __typename: 'Todo' }
        ])
      };
      cache.writeQuery({ query, variables, data });
      return null;
    };
  },
});
```

in `const current = client.readQuery({ query, variables });`

But this variable was not defined.

Plus: what is the difference between variables `client` and `cache`?

**Comment by jamiter** [comment]
client is an ApolloClient.

cache is (most of the time) the [InMemoryCache](https://github.com/apollographql/apollo-client/tree/master/packages/apollo-cache-inmemory)

**Comment by mergebandit** [comment]
Yes but the client hasn’t been initialized yet. This code generates a link which is presumably joined / concatenation to other links and then passed to the Apollo client constructor.

**Comment by mergebandit** [comment]
Further, the example contains a reference to an undeclared query variable. I’m working on a reference implementation for my team today - using the tests to figure out how this actually works. I’ve built a working query and am now working through mutation. Will update with a working example when I’m done

**Comment by robhung** [comment]
Based on his example [here](https://github.com/jbaxleyiii/todo-apollo/blob/master/src/schema/todos.js), it's meant to be `cache` and not `client`. Seems like a typo that needs to be corrected.

**Comment by solemidas** [comment]
Has anyone here implemented this with react or angular? If so can you share it with me? Thanks.

**Comment by robhung** [comment]
@solemidas The to-do list example above is using React.

**Comment by solemidas** [comment]
@robhung I meant like a full example of it, I am new to grapql was a whole I have been using redux, just wanted ton know how to use this to replace redux.

**Comment by detrohutt** [comment]
@solemidas the example he mentioned is a full example. He linked to a specific file in the repo but it’s a full app made with create-react-app.
