### ISSUE TITLE
please explain variables passed to mutation methods

### ISSUE THREAD

**Issue by barbalex** [apollographql/apollo-link-state#107]
in

```js
const local = withClientState({
  Query: {
    // provide an initial state
    todos: () => [],
  },
  Mutation: {
    // update values in the store on mutations
    addTodo: (_, { message, title }, { cache }) => {
      const current = client.readQuery({ query, variables });
      const data = {
        todos: current.todos.concat([
          { message, title, __typename: 'Todo' }
        ])
      };
      cache.writeQuery({ query, variables, data });
      return null;
    };
  },
});
```

in line in `addTodo: (_, { message, title }, { cache }) => {` it would be very helpful to know exactly what `_` and `{ cache }` are

**Comment by jbaxleyiii** [comment]
@barbalex of course! The `_` is a placeholder variable, but represents any data from the parent resolver. The `{ cache }` shows how to pull the `cache` from apollo-client off of the context. These functions `addTodo: Function` are graphql resolvers. You may be able to find some information [here](https://www.apollographql.com/docs/graphql-tools/resolvers.html) until we document this library!

**Comment by barbalex** [comment]
@jbaxleyiii thanks a lot!

I am a complete resolver noob because I am simply using [postgraphql](https://github.com/postgraphql/postgraphql) to do that for me on the backend.

So your explanation and link help a lot.
