### ISSUE TITLE
Mutations cache write without the need for the query

### ISSUE THREAD

**Issue by bogdansoare** [apollographql/apollo-link-state#108]
It would be nice for simple mutations that don't depend on data from the cache to have the ability to write directly to the cache without the need for the query.

I tried to do something like @peggyrayzis did in her talk with `cache.write` but it didn't work.
<img width="511" alt="screen shot 2017-11-15 at 11 04 02" src="https://user-images.githubusercontent.com/2750170/32827435-dc6e8190-c9f4-11e7-973b-650743a4f1ad.png">

Here is the code that I've tried. Is it possible to write to the cache without the query?
```javascript
const stateLink = withClientState({
  Query: {
    modal: () => ({
      __typename: 'Modal',
      open: false,
      info: null
    }),
  },
  Mutation: {
    openModal: (_, { info }, { cache }) => {
      const result = {
        open: true,
        info
      }

      cache.write({
        dataId: 'modal',
        result
      });
      return result;
    }
  },
});
```

**Comment by peggyrayzis** [comment]
Thanks for reporting this @bogdansoare! We're going to be adding a new method to the cache API that will let you do exactly that. Sorry it's not available yet!

**Comment by bogdansoare** [comment]
@peggyrayzis awesome, thank you and @jbaxleyiii for the great work on apollo client ❤️

**Comment by jbaxleyiii** [comment]
@bogdansoare in the interim, you can used `writeFragment` and `writeQuery` from the client API to write without a query!
