### ISSUE TITLE
Added graphql-tag to README.md

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#11]
I added `graphql-tag` in README.md.

It's not working: `import { gql } from 'react-apollo';`

**Comment by jbaxleyiii** [comment]
➤ meteor-bot commented:

@marcelodeveloper: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Meteor Contributor Agreement here: https://contribute.meteor.com/

**Comment by marcelodeveloper** [comment]
I alredy did it @jbaxleyiii
