### ISSUE TITLE
how to group state values

### ISSUE THREAD

**Issue by barbalex** [apollographql/apollo-link-state#111]
Now that I have learned how to create single state values (https://github.com/apollographql/apollo-link-state/issues/10) I would like to take this one step further: group values to organize local state better.

I imagine something like this:

localStateLink.js:
```js
export default withClientState({
  Query: {
    // I really don't know how to do this
    // but let's just try something:
    treeFilter: () => ({
      text: () => '',
      id: () => null,
    }),
  },
  Mutation: {
    // how?
})
```

...instead of:
```js
export default withClientState({
  Query: {
    treeFilterText: () => '',
    treeFilterId: () => null,
  },
  Mutation: {
    setTreeFilterText: (_, { value }, { cache }) => {
      cache.writeQuery({
        query: gql`
          query treeFilterTextQuery {
              treeFilterText @client
          }`,
        data: { treeFilterText: value },
      })
      return null
    },
    setTreeFilterId: (_, { value }, { cache }) => {
      cache.writeQuery({
        query: gql`
          query treeFilterIdQuery {
              treeFilterId @client
          }`,
        data: { treeFilterId: value },
      })
      return null
    },
})
```

How could this be done?

**Comment by jbaxleyiii** [comment]
@barbalex that should work as you have it written? Is it not?

**Comment by barbalex** [comment]
Nope. Or maybe I did not do it correctly: I added above code and expected to be able to query values using GraphiQL. But that did not work. Well, I did not know how to do it correctly and tried for instance:

```graphql
{
  treeFilterText @client
  treeFilter @client {
    text @client
  }
}
```

The result was:
```json
{
  "data": {
    "treeFilterText": ""
  },
  "loading": true,
  "networkStatus": 1,
  "stale": false
}
```

So only the method using simple variables returned data.

I also expected to see the state variables in apollo dev tool in the root query. But did not see anything.

I then tried to query the data in the app but got errors.

**Comment by barbalex** [comment]
I _think_ I got it:

localStateLink.js:
```js
export default withClientState({
  Query: {
    treeFilter: () => ({
      text: '',
      id: null,
      __typename: 'TreeFilter',
    }),
  },
  Mutation: {
    setTreeFilter: (_, { id, text }, { cache }) => {
      const treeFilter = { id, text, __typename: 'TreeFilter' }
      cache.writeQuery({
        query: treeFilterGql,
        data: { treeFilter },
      })
      return null
    }
  }
})
```

treeFilterGql.js:
```js
import gql from 'graphql-tag'

export default gql`
  query treeFilterQuery {
    treeFilter @client {
      text @client
      id @client
    }
  }
`
```

treeFilterMutation.js:
```js
import gql from 'graphql-tag'

export default gql`
  mutation setTreeFilter($text: String, $id: Uuid) {
    setTreeFilter(text: $text, id: $id) @client
  }
`
```

I'll close the issue but please correct me if there is an error in my solution.

**Comment by jbaxleyiii** [comment]
@barbalex you shouldn't need the nested `@client` directives 👍

**Comment by barbalex** [comment]
...which leads to:

treeFilterGql.js:
```js
import gql from 'graphql-tag'

export default gql`
  query treeFilterQuery {
    treeFilter @client {
      text
      id
    }
  }
`
```

Thanks @jbaxleyiii

**Comment by jzahka** [comment]
@jbaxleyiii is it possible to use `writeFragment` instead of `writeQuery` for updating a top level grouped state like this? 

I'm not sure what the `id` would be. in `writeFragment({ fragment, id, data })`

**Comment by goldenbearkin** [comment]
the id would concat the __typename and id with colon.
e.g. TreeFilter:idOfThatObject
