### ISSUE TITLE
local state does not seem to exist before it has been queried

### ISSUE THREAD

**Issue by barbalex** [apollographql/apollo-link-state#113]
It looks like state is not initialized before it has been queried once, even though `withClientState` provides - according to the readme - initial state.

I can see this in two places:

- unqueried state variables are not shown in apollo dev tool
- when state variables mutations depend on other state variables that have not yet been queried, this error occurs:
  `Unhandled Rejection (Error): Network error: Can't find field exportRcoProperties on object (ROOT_QUERY)`

This is my withClientState function where this error occurs:
```js
export default withClientState({
  Query: {
    // provide initial state
    exportTaxProperties: () => [],
    exportPcoProperties: () => [],
    exportRcoProperties: () => [],
    exportTooManyProperties: () => false,
  },
  Mutation: {
    addExportTaxProperty: (_, { taxName, pName }, { cache }) => {
      const currentTax = cache.readQuery({ query: exportTaxPropertiesGql })
      /**
       * TODO:
       * next call errors with message:
       * Unhandled Rejection (Error): Network error: Can't find field exportRcoProperties on object (ROOT_QUERY)
       **/
      const currentRco = cache.readQuery({ query: exportRcoPropertiesGql })
      const currentPco = cache.readQuery({ query: exportPcoPropertiesGql })
      const nrOfPropertiesExported =
        currentTax.exportTaxProperties.length +
        currentRco.exportRcoProperties.length +
        currentPco.exportPcoProperties.length
      if (nrOfPropertiesExported > constants.export.maxFields) {
        // TODO: set exportTooManyProperties true
      } else {
        cache.writeQuery({
          query: exportTaxPropertiesGql,
          data: {
            exportTaxProperties: [
              ...currentTax.exportTaxProperties,
              { taxName, pName, __typename: 'ExportTaxProperty' },
            ],
          },
        })
      }
      return null
    },
    addExportPcoProperty: (_, { pCName, pName }, { cache }) => {
      ...similar to addExportTaxProperty
    },
    addExportRcoProperty: (_, { pCName, pName }, { cache }) => {
      ...similar to addExportTaxProperty
    },
  },
})
```

Is this behaviour intended?

It basically means that I have to query all local state at the start of the app to prevent errors.

**Comment by allpwrfulroot** [comment]
Encountering the same with a React Native app, the entire app crashes with zero error output. Difficult to debug.

**Comment by jbaxleyiii** [comment]
@barbalex @allpwrfulroot that is definitely not the intent at all! I'll see if I can debug it, would you be able to extract a small reproduction?

**Comment by barbalex** [comment]
o.k., this is my go at demonstrating it:

- https://codesandbox.io/s/l5qn8706x9 demonstrates what happens in my project: variable 'exportTaxProperties' has been initialized by querying it. But dependant variable 'exportRcoProperties' has not been queried yet and so is not initialized and provokes an error.

- https://codesandbox.io/s/llk6wrk04m demonstrates that variable 'exportTaxProperties' is not initialized if it has not been queried yet. And so provokes an error.

- https://codesandbox.io/s/91w8p4yr9y shows everything working as expected when the variable is not an array of objects but a simple variable

**Comment by allpwrfulroot** [comment]
Just open sourced a demo React Native app that showcases this functionality: https://github.com/allpwrfulroot/yaba-social

Feel free to mess with the apollo.js file to break things in different ways: sometimes you get errors thrown, sometimes red screens, and sometimes full crash. But I LOVE the direction and will point more people towards this library. How else can I help?

**Comment by barbalex** [comment]
I just realized: This is also the reason for a different error I get:

I have an `appQuery` that queries a lot of data from the graphql server. In order to query `exportRcoProperties` and the other local state variables I added them to this query.

I quickly got lots of trouble and eliminated most local state variables again. But kept `exportRcoProperties` as that seemed to work.

Then I had this weird problem where I kept getting this error:

```bash
DOMException: Failed to execute 'postMessage' on 'Window': TypeError: Cannot add property nodes, object is not extensible could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:14:14)
    at QueryManager.onBroadcast (http://localhost:3000/static/js/bundle.js:2224:27)
    at QueryManager../node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:3000/static/js/bundle.js:3290:14)
    at http://localhost:3000/static/js/bundle.js:2868:31
    at <anonymous>
```

...followed by this:
```bash
Network error: Cannot add property nodes, object is not extensible
    at new ApolloError (ApolloError.js:34)
    at ObservableQuery../node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.currentResult (ObservableQuery.js:87)
    at GraphQL.dataForChild (react-apollo.browser.umd.js:542)
    at GraphQL.render (react-apollo.browser.umd.js:592)
    at finishClassComponent (react-dom.development.js:7902)
    at updateClassComponent (react-dom.development.js:7879)
    at beginWork (react-dom.development.js:8253)
    at performUnitOfWork (react-dom.development.js:10244)
    at workLoop (react-dom.development.js:10308)
    at HTMLUnknownElement.callCallback (react-dom.development.js:540)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:579)
    at invokeGuardedCallback (react-dom.development.js:436)
    at renderRoot (react-dom.development.js:10386)
    at performWorkOnRoot (react-dom.development.js:11000)
    at performWork (react-dom.development.js:10952)
    at requestWork (react-dom.development.js:10861)
    at scheduleWorkImpl (react-dom.development.js:10744)
    at scheduleWork (react-dom.development.js:10706)
    at Object.enqueueForceUpdate (react-dom.development.js:6242)
    at GraphQL../node_modules/react/cjs/react.development.js.Component.forceUpdate (react.development.js:244)
    at GraphQL.forceRenderChildren (react-apollo.browser.umd.js:510)
    at next (react-apollo.browser.umd.js:485)
    at Object.handleError [as error] (react-apollo.browser.umd.js:489)
    at SubscriptionObserver.error (zen-observable.js:174)
    at ObservableQuery.js:326
    at Array.forEach (<anonymous>)
    at Object.error (ObservableQuery.js:326)
    at QueryManager.js:284
    at QueryManager.js:655
    at Array.forEach (<anonymous>)
    at QueryManager.js:654
    at Map.forEach (<anonymous>)
    at QueryManager../node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (QueryManager.js:649)
    at QueryManager.js:226
    at <anonymous>
```

The first error seems to be a devtools issue caused by the underlying apollo-link-state issue: https://github.com/apollographql/apollo-client-devtools/issues/64

The second one happens when I add local state to the appQuery.

I will try to build a reproducible demo.

**Comment by barbalex** [comment]
Hm. Trying to demo above problem I queried all local state variables in the sandbox (https://codesandbox.io/s/k3yv0qp2xr) and get this error:

```bash
Invariant Violation
Objects are not valid as a React child (found: object with keys {taxName, pName, __typename}). If you meant to render a collection of children, use an array instead.
    in span (created by App)
    in p (created by App)
    in main (created by App)
    in App (created by Apollo(App))
    in Apollo(App)
    in QueryRecyclerProvider (created by ApolloProvider)
    in ApolloProvider
```

I don't know what to do of this. Maybe someone else? Maybe I am doing some nooby mistake?

**Comment by barbalex** [comment]
If I do not add

```js
exportTaxProperties @client {
  taxName
  pName
}
```

to the existing `appQuery` that also queries the graphql server, but rather add it as extra query:

app.js:
```js
const exportTaxPropertiesData = graphql(exportTaxPropertiesGql, {
  name: 'exportTaxPropertiesData',
})
```
where exportTaxPropertiesGql is:
```js
import gql from 'graphql-tag'

export default gql`
  query exportTaxPropertiesQuery {
    exportTaxProperties @client {
      taxName
      pName
    }
  }
`
```

...and do that for all local state variables,

I can circumvent the problem that they have not yet been initiated while also circumventing the `object is not extensible` error that arises when they are added to the `appQuery`.

So for the time being that is my solution.

**Comment by steve-a-jones** [comment]
@barbalex - Looks like your invariant violation is due the fact that you're rendering an array as a jsx fragment instead of mapping that array to child fragments..

You have..
```javascript
<span>{data.exportTaxProperties}</span>
```

Should be something more like..

```javascript
<span>{data.exportTaxProperties.map(({taxName, pName}) => `${taxName}, ${pName}`)}</span>
```

**Comment by barbalex** [comment]
Yep, thanks for that. So that _was_ a nooby mistake.

**Comment by steve-a-jones** [comment]
This issue appears to be related - https://github.com/apollographql/apollo-client/issues/1701. 

@jbaxleyiii - is this fix here just to opaquely call cache.writeQuery with the initial state upon initialization?

**Comment by steve-a-jones** [comment]
@barbalex - Looks like this is fixed in 0.3.0 - you can now supply a `defaults` config for initial values.

@barbalex @peggyrayzis - Is there a specific reason that the `resolvers` in `Query` aren't used to determine `defaults`

Can anyone tell that i'm excited about this project? ;)

**Comment by barbalex** [comment]
@steve-a-jones Sounds good. How would one define the defaults?

**Comment by barbalex** [comment]
By the way: This project (and apollo in general) is mind blowing great.

Sorry for being off topic.

**Comment by steve-a-jones** [comment]
Agreed! Examples are surely in the pipeline - the apollo team seems to be hard at work on this.

Have a look at these tests https://github.com/apollographql/apollo-link-state/blob/master/packages/apollo-link-state/src/__tests__/initialization.ts  for a few examples.

**Comment by peggyrayzis** [comment]
@barbalex @steve-a-jones We had defaults in the Query resolvers originally, but we needed a way to write them to the cache before executing any operations.

The example apps are updated (check the todo one) w/ the new API 😀 

Super pumped you both are loving the project!! 🎉

**Comment by peggyrayzis** [comment]
Also, docs will be live in about 10 mins :) I'll post a link when they are

**Comment by peggyrayzis** [comment]
https://www.apollographql.com/docs/link/links/state.html we have docs!!! Can I close this issue now that it's been addressed in the new version?

**Comment by barbalex** [comment]
Wow

**Comment by peggyrayzis** [comment]
Blog post: https://dev-blog.apollodata.com/the-future-of-state-management-dd410864cae2

🎉 :shipit: 🍻

**Comment by steve-a-jones** [comment]
Boom! Nice work! Meet the evolution of redux..
