### ISSUE TITLE
Document persistence strategies

### ISSUE THREAD

**Issue by kachkaev** [apollographql/apollo-link-state#119]
I've tried replacing one of my redux reducers with `apollo-link-state` queries and mutations and the result looks pretty nice. What I'm not sure though is how to persist the data between page reloads. It'd be great if README contained a link to some thoughts on this.

**Comment by reicheltp** [comment]
Persistence is not directly related to `apollo-link-state`. It is more a problem which should be solved by your cache. You can persist your whole cache with libs like [`apollo-cache-persist`](https://github.com/jamesreggio/apollo-cache-persist).

If you like to persist some minimal data just use the local storage within your mutations and in your query to acquire the initial values.

**Comment by jbaxleyiii** [comment]
@kachkaev @reicheltp for sure! When we write up our formal docs for this persistence will play a big part! For now [apollo-cache-persist](https://github.com/jamesreggio/apollo-cache-persist) and the apollo blog are places to keep an eye one ;)

Should be an announcement today if I'm not mistaken #apollodaysofchristmas

**Comment by allpwrfulroot** [comment]
I'm implementing all of this, btw, keep it coming! All your work is super appreciated.

Will repay by keeping a demo React Native app updated to show people how it all gets implemented? :smile:

**Comment by stubailo** [comment]
I think https://github.com/apollographql/apollo-cache-persist is the solution here!
