### ISSUE TITLE
Not able to access cache in apollo-link-error

### ISSUE THREAD

**Issue by goldenbearkin** [apollographql/apollo-link-state#120]
My use case is if the network status code is 4XX, log user out by mutating the local state.
Even though the status code is 4XX, i can't access the cache.
```js
onError(({ operation, networkError }) => {
    const { cache } = operation.getContext();
    console.log(cache); // undefined
})
```

seems cache is not available in the afterware?

**Comment by goldenbearkin** [comment]
As a hack, I capture the client object which is get hoisted.  But obviously, this is definitely not desirable.
```js
const link = ApolloLink.from([
  onError(({ operation, networkError }) => {
    const { cache } = operation.getContext();
    console.log(cache); // undefined
    console.log(client.cache); // ok
  }),
  createHttpLink({ uri: 'https://example.com' }),
]);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache() as ApolloCache<NormalizedCacheObject>,
});
```

**Comment by jbaxleyiii** [comment]
@goldenbearkin I'm pretty sure this was actually an issue with apollo-link itself! I've fixed that in the latest apollo-link version and will update this lib to use the newer version!
