### ISSUE TITLE
SSR Rendering (with apollo-link-state and w/o a graphQL back-end)

### ISSUE THREAD

**Issue by peter-mouland** [apollographql/apollo-link-state#125]
**Intended outcome:**

To fetch data on the server using apollo-link-state and no graphQL back-end.  Here is the guide I was _attempting_ to follow:
https://github.com/apollographql/apollo-client/blob/master/docs/source/recipes/server-side-rendering.md

**Actual outcome:**

When trying to create a `new ApolloClient` on the server, the link option seems to be giving me problems.  I have read about 3 different methods and each one returns an error:
 * `link: new SchemaLink({ schema }),`: `Schema must be an instance of GraphQLSchema`
 * `link: withClientState({ schema }),`: `TypeError: Cannot read property 'getGame' of undefined`
 * `link: createHttpLink({ ... })`: `Network error: Unexpected token N in JSON at position 0 ` (this is actually a 404)

I have checked and only have one version of graphql installed:
```
yarn list graphql*
├─ graphql-anywhere@4.1.0
├─ graphql-tag@2.6.0
└─ graphql@0.11.7
```

**How to reproduce the issue:**

I was originally adding this to an existing app, using the following additions:
 * add Apollo Link State (working client side): 
https://github.com/peter-mouland/react-lego/commit/58c920ed10d97e7c4e0a5c8e70f1580b3ce30e06
 *  trying to get SSR w/ data fetching working:
https://github.com/peter-mouland/react-lego/commit/ee32909164d661aa0bdaf26e5feca1cc1fc5a96a

Here is a reduced test case (which includes a readme highlighting important files):
https://github.com/peter-mouland/react-lego/tree/apollo-ssr-error

**Version**
- apollo-client@2.0.4

**Linked Issue within apollo-client**
Sorry, I'm not sure which repo is best suited for this issue, so i've created 2. Feel free to close if this is best answered elsewhere!
https://github.com/apollographql/apollo-client/issues/2745

**Comment by peggyrayzis** [comment]
This sounds like it's an error with `apollo-link-schema` and not this package. Can you please just post the errors you're experiencing with `apollo-link-state`?

**Comment by sebnyberg** [comment]
I was having similar issues in Next.JS when implementing SSR with Apollo Link State.

Issuing the query 

```JavaScript
query GetTodosAndButtonStatus {
  buttonStatus @client
  allTodos {
    id
  }
}
```
Resulted in the error: 

```
message: "Cannot read property 'buttonStatus' of undefined"
stack: "TypeError: Cannot read property 'buttonStatus' of undefined
  2018-01-14T15:19:16.963Z app:initApollo Network Error: TypeError: Cannot read property 'buttonStatus' of undefined
      at resolver (/mnt/c/Users/USER/code/descent-web/node_modules/apollo-link-state/lib/index.js:44:42)
      at /mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:132:32
      at step (/mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:31:23)
      at Object.next (/mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:12:53)
      at /mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:6:71
      at new Promise (<anonymous>)
      at __awaiter (/mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:2:12)
      at executeField (/mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:119:12)
      at /mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:73:48
      at step (/mnt/c/Users/USER/code/descent-web/node_modules/graphql-anywhere/lib/graphql-async.js:31:23)
```

What did work however was to separate the two queries and use `compose`. 

I uploaded an [Example Project](https://github.com/sebnyberg/apollo-link-state-ssr-error) with the error and solution.

**Comment by enyce12** [comment]
SSR is working fine for me and I don't receive any errors. Maybe this was fixed. But I get warnings when exceuting the following query in the browser:
```
graphql(gql`
  {
    userInfo {
      username
    }

    ui @client {
      navigationVisible
    }
  }
`),
```

Warning: ```Missing field ui in { "userInfo": { ...```

The result looks fine, though. Because I've all my graphql queries in separate files  (one per React component) and would have to create for each client query a second file I'll stick with the warning message and hope this will be fixed in V1 :)

**Comment by hwillson** [comment]
This should be working with current day versions of `apollo-client`, `apollo-link-state` and `apollo-link` (this has been reported to be working by others since this issue was opened). I'll close this for now, but if you're still encountering this issue, let us know. Thanks!
