### ISSUE TITLE
TypeError when refetching a query

### ISSUE THREAD

**Issue by blissi** [apollographql/apollo-link-state#139]
Hallo,
I have defined a default state and a resolver like this:
```javascript
export const CoreDefaults = {
	networkStatus: {
		__typename: "NetworkStatus",
		isConnected: false
	}
};

export const CoreResolvers = {
	Mutation: {
		updateNetworkStatus: (_, {isConnected}, {cache}) => {
			...
		}
	}
};
```

When I simply perform or watch a query, everything works. But when I perform a mutation and specify to refetch the query, a TypeError is thrown. The code basically looks like this:
```javascript
const IS_CONNECTED_QUERY = gql(`
query isConnected {
	networkStatus @client {
		isConnected
	}
}
`);
...
this._isConnected$ = this.apollo.watchQuery({query: IS_CONNECTED_QUERY})
                                   .valueChanges
                                   .map(({data}: any) => data.networkStatus.isConnected);
...
this.apollo.mutate({
			mutation: SET_IS_CONNECTED,
			variables: {
				isConnected
			},
			refetchQueries: [{
				query: IS_CONNECTED_QUERY
			}]
		}).subscribe();
```

Error details:
```javascript
Error: Uncaught (in promise): TypeError: Cannot read property 'networkStatus' of undefined
TypeError: Cannot read property 'networkStatus' of undefined
    at resolver (http://localhost:4300/vendor.bundle.js:125666:66)
    at http://localhost:4300/vendor.bundle.js:131662:32
    at step (http://localhost:4300/vendor.bundle.js:131563:23)
    at Object.next (http://localhost:4300/vendor.bundle.js:131544:53)
...
```
I debugged it a bit and the line of code in GraphQL that throws is
`
var resolve = resolvers[rootValue.__typename || type][info.resultKey || fieldName];
`

That's because I don't have a "Query" field within my resolver definition. If i add it (and leave it empty), an error message "Missing field networkStatus in {}" is logged to the console.

Thus, I would have to add a query resolver for networkStatus to my resolvers definition.
Is this a bug or intended behavior? It isn't documented anywhere and I to me it seems to be quite a burden to define a query for each state.

Thanks,
Steven

**Comment by steve-a-jones** [comment]
@blissi Can you provide your definition for your `SET_IS_CONNECTED ` mutation? It should look something like 

```javascript
mutation SetIsConnected (...) {
   updateNetworkStatus(...) @client {
     ...
  }
}
```

**Comment by blissi** [comment]
It looks like this:
```javascript
const SET_IS_CONNECTED = gql(`
mutation updateNetworkStatus($isConnected: Boolean) {
	updateNetworkStatus(isConnected: $isConnected) @client
}
`);
```

It's kind of strange: I added a success and a failed callback to the subscribe()-call of the mutation. The mutation always succeeds.
Then I did this for the query side, too. When the error occurs, neither subscribe callback gets called.
But this occurs only once: when I trigger the mutation again, the error message doesn't occur again and the query subscribe-callbacks get called again.

**Comment by agborkowski** [comment]
did u set a initial state ?

**Comment by blissi** [comment]
yes (CoreDefaults in first post).

**Comment by agborkowski** [comment]
actualy im starting r&d eagsacly what u did, ill give u feedback how is go on or not :)

**Comment by hwillson** [comment]
Any chance you could provide a small runnable reproduction that shows this happening? A reproduction here would greatly help with troubleshooting. Thanks!

**Comment by blissi** [comment]
Sorry, I removed apollo-link-state and am now managing my state in ngrx completely.

**Comment by hwillson** [comment]
Closing based on https://github.com/apollographql/apollo-link-state/issues/139#issuecomment-399853801. If anyone else encounters this issue and can provide a small runnable reproduction, we'll take a look.
