### ISSUE TITLE
querying local and remote data together seems to break things

### ISSUE THREAD

**Issue by anomaly44** [apollographql/apollo-link-state#154]
I'm pretty new to apollo so it might just be me, but it seems there is something weird happening when I try to query from both local and remote sources.
this snippet works as expected
```javascript
const GET_AUTH = gql`
query {
  auth @client {
    adminLevel
  }
}
`;
```
this one does aswell:
```javascript
const GET_AUTH = gql`
query {
  user(id: 1) {
    id
    email
  }
}
`;
```
when I combine them i get: 
`Uncaught (in promise) TypeError: Cannot read property 'auth' of undefined
    at resolver (index.js:26)`

```javascript
const GET_AUTH = gql`
query {
  auth @client {
    adminLevel
  }
  user(id: 1) {
    email
  }
}
`;
```

This is the same pattern as in the apollo-link-state docs where `networkStatus` and `articles` are queried together.

Am I missing something or is this a bug?

**Comment by johannesfritsch** [comment]
This seems to be a duplicate of #140

**Comment by peggyrayzis** [comment]
Let's move discussion over to #140 :)
