### ISSUE TITLE
Get the store object, to pass down to navigation router just like Redux store

### ISSUE THREAD

**Issue by juicycleff** [apollographql/apollo-link-state#159]
Please what is the substitute for this

`// create our store
const store = createStore()

//Wix RNav
registerScreens(store, Provider);`

in link state

**Comment by steve-a-jones** [comment]
@juicycleff - 

The "store" exists in Apollo Cache and you issue queries/mutations against the cache using the special `@client` directive.

I believe the idea here is to leverage Apollo's "automatic store updates" - which will rerun queries (in this case local queries with the `@client` directive) when mutations are made against the same `@client` type (or fragments).

Is this what you're looking for? You may need to do some experimenting to integrate with your router. @peggyrayzis may have more insights :)

Here are some great resources to get started:

https://dev-blog.apollodata.com/the-future-of-state-management-dd410864cae2
https://www.apollographql.com/docs/react/features/cache-updates.html#automatic-updates
https://www.apollographql.com/docs/link/links/state.html#start
https://www.youtube.com/watch?v=eHjP2WFt0zU

**Comment by peggyrayzis** [comment]
Thanks for your response @steve-a-jones! Closing since this is out of the scope of this project.
