### ISSUE TITLE
cache.readQuery errors with "Can't find field test on object (ROOT_QUERY) { ... }"

### ISSUE THREAD

**Issue by mathiasjakobsen** [apollographql/apollo-link-state#161]
I have a paginated Query type called `getNotes`, on my server - which looks something like this:

```graphql
  query getNotes($cursor: String) {
    viewer {
      notes(first: 50, after: $cursor) {
        edges {
          node {
            id
            content
          }
        }
      }
    }
  }
```

After this has executed, I will have a cache root containing something like:
```json
"ROOT_QUERY.viewer.notes({"first":50,"after":null}).edges.6": {
  "node": {
    "generated": false,
    "id": "Note:64e5fa13-e81a-4882-bff2-e8886beca99e",
    "type": "id",
    "__typename": "NoteEdge"
  }
}
```
... and then the actual object also ...
```json
"Note:64e5fa13-e81a-4882-bff2-e8886beca99e": {
   "id": "64e5fa13-e81a-4882-bff2-e8886beca99e",
   "content": "Hi there!",
  "__typename": "Note",
}
```

How would I manage to use `cache.readQuery` to query **ALL** the memories in my cache? (Hence, all objects in cache with the id format `Note:[id]`). The cursor is obviously changing each time I'm fetching more notes from the server, so when I have to define the query I'm using in `cache.readQuery({ query })` I don't know how to structure the query, since I don't know which `ROOT_QUERY.viewer.notes({"first":50,"after":null}).edges.6`like key, it was stored under in the first place.

I hope you guys can help, solve this! :rocket:

**Comment by peggyrayzis** [comment]
Hi, can you please open this issue on the Apollo Client repo since it deals with server data? In the meantime, here is our documentation on [pagination](https://www.apollographql.com/docs/react/recipes/pagination.html) to get you started.

**Comment by mathiasjakobsen** [comment]
@peggyrayzis I found out that this is related to https://github.com/apollographql/apollo-client/issues/2051#issuecomment-341696989, so we'll move it over there.
