### ISSUE TITLE
Warnings with example code snippets

### ISSUE THREAD

**Issue by akiran** [apollographql/apollo-link-state#176]
When I tried to follow to code snippets in the readme, I got below warnings
```
Missing field __typename in {
  "isConnected": false
}
Missing field updateNetworkStatus in {}
```
I found a solution to prevent these warnings. 
I will open a PR updating the example shortly.

**Comment by wowzaaa** [comment]
does returning null solve it?

**Comment by akiran** [comment]
@wowzaaa returning null solved 1 warning but still getting type warning
```
Missing field __typename in {
  "isConnected": false
}
```

**Comment by akiran** [comment]
@wowzaaa Can you check this PR https://github.com/apollographql/apollo-link-state/pull/177
which is better ? returning null or data.networkStatus
Both fixes 
```Missing field updateNetworkStatus in {}```

**Comment by wowzaaa** [comment]
well i am one of the early adopters of apollo-link-state ... that was the first issue i encountered 
i saw that returning something made the warning go away ... the pb is that i do not know the implications so i was not that happy with any of the solutions

if u look at the video by Sara Vieira [https://www.youtube.com/watch?v=2RvRcnD8wHY&feature=youtu.be](https://www.youtube.com/watch?v=2RvRcnD8wHY&feature=youtu.be) you will see that is says nothing about the warning so i left it like this for now

my next problem appeared now ... when i want to persist the cache ... and i was checking if i can use apollo link state and apollo cache persist toghether .... i did not manage to make them talk to each other but i am still asking myself about the implications of that return
- maybe u use that when u try to return something from the mutation
- and for my problem ... maybe returning something from the mutation will trigger apollo persist cache to actually write to cache the returned value

unfortunately I cannot say for sure which one it is :(

**Comment by peggyrayzis** [comment]
Thanks for sending in the PR, I'm going to close this issue.
