### ISSUE TITLE
2.0.0 requires unstated dependency @types/lodash.flowright

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#18]
**Intended outcome:**
Upgrading from 1.x release to the 2.x release. 

**Actual outcome:**

    Error at node_modules/react-apollo/browser.d.ts:6:26: Could not find a declaration file for module 'lodash.flowright'. '/Users/x/x/node_modules/lodash.flowright/index.js' implicitly hasan 'any' type.
      Try `npm install @types/lodash.flowright` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.flowright';`**How to reproduce the issue:**

Install react apollo in a typescript project and run tsc

**Version**

* apollo-client@2.0.1
* react-apollo@2.0.0

**Comment by jbaxleyiii** [comment]
➤ Nhat Khanh commented:

Confirm error

**Comment by jbaxleyiii** [comment]
➤ Cory Deppen commented:

It looks like the compiler didn't catch this (and many other instances like it) because the noImplicitAny compiler option isn't being used. Unfortunately, installing @types/lodash.flowright won't resolve it and results in an error [ts] Module '"/path/to/node_modules/@types/lodash.flowright/index"' resolves to a non-module entity and cannot be imported using this construct.

Using the [`lodash-es` package](https://www.npmjs.com/package/lodash-es) (instead of lodash or lodash.flowright) along with the [@types/lodash-es package](https://www.npmjs.com/package/@types/lodash-es) will allow specific functions to be imported in ES modules and compile without error when the noImplicitAny compiler option is used.

  * import * as compose from 'lodash.flowright'; 
  * export { compose }; 
+ import flowRight from 'lodash-es/flowRight';
+ export { flowRight as compose };If there is agreement on this approach, I don't mind working on a PR.

**Comment by jbaxleyiii** [comment]
➤ Inaki Anduaga commented:

Same error here. The Typescript type definition errors are kinda ruining the fun of experimenting  with an apollo integration

**Comment by jbaxleyiii** [comment]
➤ Eitan Yarmush commented:

Just encountered this same error and used the above fix in my node_modules. Have you started a PR for this? @corydeppen

**Comment by jbaxleyiii** [comment]
➤ Cory Deppen commented:

Not yet. I wanted to see if there was agreement on the approach first, but haven't heard anything yet.

**Comment by jbaxleyiii** [comment]
➤ Jurosh commented:

@inakianduaga it's kinda is. Hope this will be resolved soon. For now probably best to downgrade to 1.4.16 where typings are just fine. Migration back to v2 should be quite straightforward later as looks like there aren't really many breaking changes.

**Comment by corydeppen** [comment]
Seems a few issues I've seen recently have been modified to show @jbaxleyiii submitted them all and included "[user] commented:" lines. I can't tell if this was intentional or not and it's a bit unusual. In some cases, they've been closed but I can't determine why and whether a PR has already been submitted and/or merged. Using this issue as an example, why was it closed and will the issue be resolved elsewhere?
