### ISSUE TITLE
fetch defaults (initialState)

### ISSUE THREAD

**Issue by andrii-m** [apollographql/apollo-link-state#182]
Could somebody help me and provide an example when defaults (initialState) not hardcoded but fetched from server?

**Comment by peggyrayzis** [comment]
The defaults are created when the link is initialized before any requests have taken place, so you won't be able to use server results.

What you can do is provide an initial state and override it when you get back your server data by calling `cache.writeData({ data: {} })`.

Can you please elaborate on your use case for needing server data for initial state?

**Comment by andrii-m** [comment]
@peggyrayzis use case can be very simple: TodoApp with server sync. I need to fetch my previously saved todos from server.

**Comment by fbartho** [comment]
Closing issue as the question was answered, and it's points to a feature request (async defaults for link-state) I don't believe is being considered at this time.
