### ISSUE TITLE
cache.writeData({ data: defaults }) error in React Native

### ISSUE THREAD

**Issue by glauberfc** [apollographql/apollo-link-state#183]
![screenshot_2018-01-24-09-39-25-401_com mellitusmobile](https://user-images.githubusercontent.com/15311858/35344407-d5b1e4ac-010b-11e8-8bec-8470ca2ebd6a.png)

```
const cache = new InMemoryCache()

const stateLink = withClientState({ resolvers, cache, defaults })

const client = new ApolloClient({
  link: ApolloLink.from([
    stateLink,
    new HttpLink({ uri: '...' })
  ]),
  cache
})
```

Does someone know how I can fix that?

**Comment by peggyrayzis** [comment]
If you're passing in the cache, you also need to pass in defaults.

https://www.apollographql.com/docs/link/links/state.html#defaults

**Comment by glauberfc** [comment]
I'm sorry. I typed the wrong code, but I already updated it. I am using defaults, but I have this error like on the image.

**Comment by peggyrayzis** [comment]
I think I know what's happening, you need to update your `InMemoryCache`. We recently added `cache.writeData` to the main cache API.

**Comment by glauberfc** [comment]
The problem was solved! Thanks!
