### ISSUE TITLE
Mutating local state inside a network query error handler results in unhandled error

### ISSUE THREAD

**Issue by rdickert** [apollographql/apollo-link-state#184]
Calling a state mutation inside a query error handler seems to cause the error to "stick" to the mutation call, making it impossible to safely change client state to handle the error.

I'm working on an app that shows a QR code scanner, which sets local client state to the QR code that was read (`SET_QR_CODE` below). I also have a component (not shown) that chooses which component to render: the qrcode if we haven't read a code (the qrcode state is empty) or the app if a code is present. Rendering the app triggers a query to the server using the qr code from client state as `variables` (`MENU_QUERY` below). 

**The problem:** If the server query throws an error, the component catches it normally, but if I try to set the local state (qr code) to `""` to show the qr code scanner again, I get an `Unhandled error` for the failed network query. Curiously, I can get the `ErrorScreen` component to render with a button that runs the state mutation via onClick, and though the error screen with button render, I still get the same error when the button is clicked!

There is a workaround - I can simply not throw an error, and communicate the problem directly to the query without throwing an exception. Running the same state mutation elsewhere works fine.

Here is some slightly simplified code that shows where the error occurs:

```js
const SET_QR_CODE = gql`
  mutation setQrCode($qrCode: String!) {
    setQrCode(qrCode: $qrCode) @client
  }
`;

const QueryContainer = ({ render, data, setQrCode }) => {
  if (data.error) {
    setQrCode(''); // if I remove this, ErrorScreen renders correctly
    // -> "Unhandled error GraphQL error: no menu items found for location"

    return <ErrorScreen error={data.error} />;
  }
  if (data.loading) {
    return <Loading />;
  }
  return render(data.menu);
};

export default compose(
  graphql(SET_QR_CODE, {
    props: ({ mutate }) => ({
      setQrCode: qrCode => mutate({ variables: { qrCode } }),
    }),
  }),
  graphql(MENU_QUERY, {
    options: { fetchPolicy: 'network-only' },
    // variable qrCode is passed in via props
  }),
)(QueryContainer);
```

**Comment by farzd** [comment]
I've been having the exact same issue for the past two weeks! The error from the network request which is handled appropriately seems to latch on for subsequent local mutations. I really hate tagging contributors because i know how busy things can get but would appreciate a hint if you get the time @peggyrayzis.

```
export const defaults = {
  checkedIn: false
}

export const resolvers = {
  Mutation: {
    checkIn: (_, args, { cache }) => {
      cache.writeData({ data: { checkedIn: true } })
      return null
    },
    checkOut: (_, args, { cache }) => {
      cache.writeData({ data: { checkedIn: false } })
      return null
    }
  },
  Query: {
    places: async (_, args, { cache }) => {
      try {
        const places = await facebook.getPlaces()
        return [...places]
      } catch (e) {
        return Promise.reject(new Error(e))
      }
    }
  }
}
```

This throws an error and it is caught appropriately 
```
 query getPlaces {
    places @client {
     ....
    }
}
```

But then same error props up when i try this
```
  mutation checkIn {
    checkIn @client
  }
```

**Comment by epatrasc** [comment]
I'm having a similar issue, i'm starting to wonder if apollo-link-state supports propagating errors per different queries/mutations ? You should be able to write error to cache as well and allow manual refetch etc !?

**Comment by farzd** [comment]
If it helps i've isolated this issue into a simple react-create-app project
https://github.com/farzd/apolloLinkStateErrorPersisting

It seems that if the resolver throws an Error again for the same component, it crashes

**Comment by farzd** [comment]
@rdickert this might be related https://github.com/apollographql/apollo-client/issues/3000

**Comment by farzd** [comment]
This seems to be fixed with "react-apollo": "^2.1.0"
You see it working https://codesandbox.io/s/nwvl41wn10
revert to older version of react-apollo in the sandbox to see the error

**Comment by rdickert** [comment]
Nice. I bypassed this issue in my code so can't test it on my end right now, but I'm happy to close this if it seems to be fixed

**Comment by hwillson** [comment]
Since it sounds like this has been fixed (https://github.com/apollographql/apollo-link-state/issues/184#issuecomment-375656940), I'll close this off. Happy to re-open if anyone is still encountering this issue. Thanks!
