### ISSUE TITLE
apollo-client-preset 1.0.7 breaks @client directive in apollo-link-state

### ISSUE THREAD

**Issue by steve-a-jones** [apollographql/apollo-link-state#186]
@peggyrayzis  - Can you confirm if you are seeing the same issue? https://github.com/apollographql/apollo-client/issues/2931

**Comment by LawJolla** [comment]
The problem is with apollo-utilities@1.0.5.  Not sure what yet, but the 1.0.5 broke @client.

**Comment by kavink** [comment]
Local state is completely busted for me, deleting does not help me.

**Comment by peggyrayzis** [comment]
Hey everyone! Please rollback apollo-client-preset to 1.0.6. We've unpublished the breaking version (1.0.7) from the registry and are working on a fix soon.

Thanks for your patience!

**Comment by krokofant** [comment]
@brunobasto I seem to have 1.0.6 installed and had the issue described in #140
