### ISSUE TITLE
Code works on codesandbox, but not on my machine

### ISSUE THREAD

**Issue by akiran** [apollographql/apollo-link-state#187]
Hi,

I am creating different examples to explore local state management with apollo. Recently, I am running into an issue where similar code work in one repo but fails in another repo.

I created a codesandbox to demostrate this issue. 
Code works in this codesandbox. 
https://codesandbox.io/s/v00rnlkr20
Button toggles between login and logout when we click on it.

But if I download the codesandbox code and run it on my machine, it fails with error
<img width="488" alt="screen shot 2018-01-30 at 7 09 14 pm" src="https://user-images.githubusercontent.com/3403295/35569090-1f626664-05f1-11e8-9f31-be79d35f3320.png">

To make sure, it is not a problem with my machine, I requested my colleague to download code and run it on his machine. It doesn't work on his machine also, but it works on codesandbox.

**Comment by LawJolla** [comment]
I continue to struggle with the same issue.  I think there's a dedupe problem somewhere in the chain.  

```
"apollo-cache-inmemory": "^1.1.5",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.2.1",
    "apollo-link": "^1.0.7",
    "apollo-link-context": "^1.0.3",
    "apollo-link-error": "^1.0.3",
    "apollo-link-http": "^1.3.2",
    "apollo-link-state": "^0.3.1",
    "apollo-utilities": "^1.0.5",
    "react-apollo": "^2.0.4"
}
```

I get the same error.  Put if I remove the carrots and pin all of the versions, it works fine.  Of course the odd part is that all of those versions are the most current.

**Comment by kavink** [comment]
@LawJolla @akiran I am facing the same issue... I cannot understand what magic is going wrong, deleting lock files and node_modules has not helped. I see an issue where defaults in Apollo-link-state do not seem to actually set default in @client namespace in local cache, Please can you see what your local data with defaults looks like ?

**Comment by kavink** [comment]
@peggyrayzis ^^ I think I found the issue. Defaults are not working on my local machine.

**Comment by LawJolla** [comment]
The defaults seem like they don't work because the @client directive is not working so the query blows up.  (I think)

Try rolling your modules back and clear your NPM cache.  I went with

```
 {
   "apollo-client": "2.0.4",
   "apollo-cache-inmemory": "1.1.0",
  "apollo-utilities": "1.0.3"
}
```

**Comment by pachomski** [comment]
having the same issue. was working fine this morning before I npm installed. : (

**Comment by kavink** [comment]
@pachomski yeah.. its a huge bug.. thats what happened to me . see workaround I just posted... #188 

@LawJolla That does not work.. I finally found a workaround after spending like 12 hours...

**Comment by pachomski** [comment]
@kavink,

Unfortunately your fix in #188 did not work for me. While it set the default state,  the mutations I had in place were not firing

**Comment by kavink** [comment]
@pachomski You also need to change your mutation data, to do the same... i.e. 
```
const data = {
    'env@client': {
    .....
   }
}

```

I just got both mutations and query working with that trick in ```withClientState```

**Comment by peggyrayzis** [comment]
The CodeSandbox isn't working locally for me either. I think it's because `apollo-client@2.2.1` is installing the latest patch version of `apollo-utilities`, which is broken. A lot of our packages depend on `apollo-utilities`, so it's likely that `apollo-link-state` is installing the latest patch too.

**Comment by akiran** [comment]
Error is happening because of this line https://github.com/apollographql/apollo-link-state/blob/master/packages/apollo-link-state/src/index.ts#L76
resolverMap is undefined.
so error is thrown because of resolverMap[fieldName] access

**Comment by peggyrayzis** [comment]
Upgrading to the latest versions of `apollo-cache-inmemory` and `apollo-link-state` should now fix this issue! Thank you all for your patience 😀
