### ISSUE TITLE
Defaults don't work anymore

### ISSUE THREAD

**Issue by kavink** [apollographql/apollo-link-state#188]
Defaults on Apollo-link-state have stopped working, no idea why. See similar issue as #187

**Comment by kavink** [comment]
Finally found a workaround .... basically when setting default 

instead of doing the following 
```
withClientState({
    cache,
    defaults: {
        env: {
            name: "prod"
        }
    }

})

```

Change it to 

```
withClientState({
    cache,
    defaults: {
        'env@client': {
            name: "prod"
        }
    }

})

```

**Comment by kavink** [comment]
@peggyrayzis if you need a working example about setting default.. https://codesandbox.io/s/mqjyyj9r9j

**Comment by steve-a-jones** [comment]
@kavink - This might be related (https://github.com/apollographql/apollo-link-state/issues/186).. I had tests breaking earlier with apollo-link-state. This is the first I am seeing `@client` syntax in defaults -- what led you to that solution?

**Comment by kavink** [comment]
@steve-a-jones I just wanted my stuff to work and it just stoped working after ```yarn install```, tried to debug a lot and finally figured out the issue was when setting defaults as per doc, it was missing ```@client``` directive in default, When I did mutation it would save with ```@client```  directive, So in Apollo state I had 2 keys , 1 ```@env``` and other after mutation ```env@client```, So I figured default one was wrong as mutation was never changing that value, So I forced default with ```@client``` and my app started working as it used it. I am waiting on permanent fix, this was just a hack to unblock myself...

**Comment by kavink** [comment]
+ I tried rolling back and all the various other stuff mentioned in radar, nothing was working for me.

**Comment by barbalex** [comment]
unfortunately this:

- does prevent all the error messages (`cannot read property...`)
- but in my app nothing happens. As if local state did not exist

**Comment by barbalex** [comment]
This comment from @kavink  saved my day: https://github.com/apollographql/apollo-link-state/issues/187#issuecomment-361753208

Please go have a beer, @kavink !

**Comment by Altiano** [comment]
My query will get the data from the `defaults` if I remove `@client` directive in query

**Comment by yellowspaceboots** [comment]
Hey everyone! As @Altiano says above removing the @client directive in query seems to allow the defaults to work. I first tried adding the 'env@client' into the defaults as @kavink suggested but for some reason this created an issue where I had both env and 'env@client' in my cache and in my mutation resolver I had to make sure i specified 'env@client' to update or my component would not see my changes. If the queries are working without the @client directive do we need it? Thanks for all the work you guys do!

**Comment by steve-a-jones** [comment]
@yellowspaceboots - I don't believe supplying the `@client` directive as a substring on `defaults` is correct syntax, @peggyrayzis correct me if i'm wrong... This is my first time seeing defaults used that way. My understanding is that you should supply `__typename` to properly identify types as shown in the readme example..

```javascript
defaults: {
    networkStatus: {
      __typename: 'NetworkStatus',
      isConnected: true,
    }
  },
```

I believe `apollo-link-state` was affected by recent updates to its package dependencies.

**Comment by kavink** [comment]
The comment I posted above is hack...to unblock myself (while using yarn).. while I wait for a permanent fix...

**Comment by Altiano** [comment]
What is working for me is, remove the `@client` directive on the query in `gql()`

**Comment by peggyrayzis** [comment]
Upgrading to the latest versions of `apollo-cache-inmemory` and `apollo-link-state` should now fix this issue! Thank you all for your patience 😀

**Comment by oqx** [comment]
This inexplicably happened to me early in the AM. After upgrading and trying a few recommended solutions, I just rolled back to a previous commit and all is working.

**Comment by thakurinbox** [comment]
@peggyrayzis I am using latest version of `apollo-cache-inmemory` and `apollo-link-state` but still its not working on my machine

**Comment by redbar0n** [comment]
@thakurinbox  Try adding `__typename: Query` to the defaults, it seemingly worked for us, and the hard-to-debug "Could not find __typename on Fragment" errors disappeared:

```
defaults: {
    __typename: Query,
    networkStatus: {
      __typename: 'NetworkStatus',
      isConnected: true,
    }
  },
```
