### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by cyrus-za** [apollographql/apollo-link-state#191]
Now that Apollo no longer uses Redux under the hood. Is it still a good idea to use redux-form? If so, what should be done differently? It feels rather bloated to install both apollo-link-state and redux.

It would be great if we had some apollo-link-state-form library that works similar to redux-form but uses the apollo store.

**Comment by peggyrayzis** [comment]
Not sure how feature complete it is, but @abhiayer91 started working on an Apollo forms library: https://www.npmjs.com/package/apollo-forms

If I were looking for something production ready today, I'd probably choose [Formik](https://github.com/jaredpalmer/formik). Hope that helps!

**Comment by kavink** [comment]
@cyrus-za I have had very good luck for my Apollo app using https://github.com/final-form/react-final-form 

Look at the comparison table if you wanna chose which fits best for you .. https://github.com/final-form/react-final-form/blob/master/docs/comparison.md

**Comment by peggyrayzis** [comment]
That chart is super helpful @kavink, thanks! Have you tried `apollo-link-state` with `react-final-form`? I'd be open to adding an example app for forms if you'd like to try creating a PR 😀

**Comment by kavink** [comment]
@peggyrayzis I wish I could , but I cannot create a sample app.

But yes, I am using ```apollo-link-state``` with ```react-final-form```

**Comment by cyrus-za** [comment]
Thanks @kavink and @peggyrayzis that is much appreciated. I stumbled on react-final-form a few minutes after creating this issue. So far it's going well for me. Glad to see its the same person that made redux-form so similar api that I am used to, without the overhead of redux. 

@kavink if you don't have time for a sample app, is there any chance you could just post a snippet here of how you go about connecting the 2 (`apollo-link-state` and `react-final-form`)

**Comment by kavink** [comment]
@cyrus-za @peggyrayzis Refer this example, replace ```save``` by Apollo mutation function.. you can use ```apollo-local-state``` to read input and pass params to ```load``` https://codesandbox.io/s/xr0mvl1904

**Comment by AhmadEl-Banna** [comment]
@cyrus-za @kachkaev Thanks for starting this discussion, but I don't see any need for apollo-link-state or any other state management library with react-final-form, it can hold form state
Did I misunderstand something?

**Comment by cyrus-za** [comment]
Ahmad you are correct. I didn't know about react final form when opening
the issue. You can close the issue
