### ISSUE TITLE
States in cache reset to defaults after browser refresh or navigation??

### ISSUE THREAD

**Issue by fodurrr** [apollographql/apollo-link-state#192]
Hi,

I wrote a small example with apollo-link-state and I realised that the states which were already mutated are reset to defaults when the page is refreshed in the browser or navigating to other page.

Why is like that?? I would expect that defaults are stored in the cache initially when those states are undefined, but later defaults should not interfere anymore with cache.

Can you check my repo? Do I use it correctly??
[https://github.com/fodurrr/apollo-link-state-example](https://github.com/fodurrr/apollo-link-state-example)

thanks in advance

**Comment by Zn4rK** [comment]
If you use a persistent cache (like https://github.com/apollographql/apollo-cache-persist) you'll get what you are looking for.

The same thing happens to a React Component's state when you refresh. If you want it to be more persistent, you'll have to use something to make it persistent.

**Comment by yellowspaceboots** [comment]
Beat me to it! :P

**Comment by Zn4rK** [comment]
This (https://github.com/apollographql/apollo-link-state/issues/170) issue is worth looking at if you are trying to use `apollo-cache-persist` with `apollo-link-state` though.

**Comment by fodurrr** [comment]
Thanks for the quick answers. I will look deeper, however I tried apollo-cache-persist but it is not really a solution alone. I also checked #170. 

Apollo-cache-persist stores my mutations nicely in localStorage but how do I synchronise from localStorage to in-memory-cache after page refresh or navigation with react router? In-memory-cache will be set back to the defaults.

What is the best way to handle page refreshes?

Thanks for help

**Comment by fbartho** [comment]
As mentioned elsewhere, this library doesn't really deal with serialization, I'm going to close this ticket for now. You might have an easier time asking on StackOverflow or chatting in Slack! (There's a #local-state channel among others!)
