### ISSUE TITLE
Custom query resolvers not working

### ISSUE THREAD

**Issue by akiran** [apollographql/apollo-link-state#196]
I tried adding query resolvers similar to mutation resolvers passed to withClientState.
But these custom resolvers are not taken into consideration and only values in cache are returned.
https://codesandbox.io/s/m5m0x9vo7x

**Comment by wowzaaa** [comment]
maybe it is not related but isn't $isLoggedIn supposed to be Boolean? ur passing 'yes' and 'no' but ur mutation expects Boolean

**Comment by akiran** [comment]
Updated the mutation argument type from Boolean to String. Still the issue exist.

**Comment by akiran** [comment]
I think, for local state query, request method at this [line](https://github.com/apollographql/apollo-link-state/blob/master/packages/apollo-link-state/src/index.ts#L41) is not getting invoked.
data is returned from cache before hitting request.

currently request method is invoked only for mutation and queries that has both server and client data access

**Comment by wowzaaa** [comment]
i've forked ur demo and tried to play around with it a bit but i cannot get it to be called by the Apollo Client

https://codesandbox.io/s/y3xzm5mk9v

so we are either missing something or custom resolvers do not work for the local store ... maybe they thought it is not useful since everything u want to do in a custom resolver you can very well do inside of ur app ...

**Comment by akiran** [comment]
Query resolvers are mentioned in the docs here
https://www.apollographql.com/docs/link/links/state.html

**Comment by wowzaaa** [comment]
so now it is being called but it does what u say it does ... it does not return the value from the resolver

https://codesandbox.io/s/y3xzm5mk9v

**Comment by jsslai** [comment]
How it should behave when cache contains `isLoggedIn` property and resolver also defines `isLoggedIn` query?

**Comment by wowzaaa** [comment]
i've just read this from the docs :))

> 4. Query resolvers are only called on a cache miss. Since the first time you call the query will be a cache miss, you should return any default state from your resolver function.

**Comment by jsslai** [comment]
So if you don't add `isLoggedIn` in initial state (defaults) it should call the query resolver.

**Comment by wowzaaa** [comment]
might be but in this case the custom resolver would still need a @client value in order to do it's job ... at least this is what i think a normal case would be ... otherwise the custom resolver would be more like a static resolver :)

**Comment by akiran** [comment]
Closing this because "Query resolvers are only called on a cache miss" is mentioned in docs

**Comment by clodal** [comment]
For future people, akiran is right. Wrap your custom Query resolver in a try-catch block. See here for an example https://github.com/apollographql/apollo-link-state/blob/master/examples/async/src/resolvers/index.js.
