### ISSUE TITLE
apollo client resetStore with apollo-link-state triggers Error: Network error: Cannot read property of undefined

### ISSUE THREAD

**Issue by wowzaaa** [apollographql/apollo-link-state#198]
I am trying this a second time because the previous issue was closed without a single test #194 
so the error is replicated here https://codesandbox.io/s/v69v13w0o0
you will see the error in the console after clicking the reset button which does client.resetStore

i really hope we can sort this out
thanks

**Comment by EQuimper** [comment]
+ 1 for me, I also did like told in the docs about putting statelink.writeDefaults and nothing change same error.

**Comment by wowzaaa** [comment]
i added client.onResetStore(stateLink.writeDefaults);

the error exists with or without this callback

**Comment by wowzaaa** [comment]
looking into the code i realized that this is actually an apollo client bug ... not related to apollo-link-state

**Comment by res84** [comment]
+1 for me...
i think same issue on #187, #194... and #195 should fix.. but i am still getting the same error even upgrading both apollo-cache-inmemory and apollo-link-state...

"apollo-cache-inmemory": "^1.1.7",
"apollo-client": "^2.2.2",
"apollo-link-state": "^0.4.0",
"apollo-utilities": "1.0.6"

**Comment by res84** [comment]
ok, i guess the trick is adding query to state resolvers like mentioned #156 by Scott (@stolinski)

**Comment by wowzaaa** [comment]
yeap :) that fixed it :)

**Comment by wKovacs64** [comment]
Maybe you are seeing different results than I, but simply adding an empty/dummy query to my resolvers map is not fixing anything. It masks the problem by causing the new (after a `resetStore()` call) `resolverMap` to exist, but the default resolvers are not present so future queries do not resolve properly, warning about `Missing field someArbitraryStateField in {}`.

**Comment by wowzaaa** [comment]
@wKovacs64 u jinxed my code ... i can swear it was working yesterday ... now indeed i get Missing field :(

here is the updated link:
https://codesandbox.io/s/v69v13w0o0

i really hope we aren't the only ones tracking this issue :)

**Comment by wKovacs64** [comment]
Maybe Apollo will clone @peggyrayzis for additional bandwidth.  😉 🤞

**Comment by evans** [comment]
@wowzaaa Thank you for opening the issues! Really appreciate the codesandbox! It made spinning up on the project really nice. Please check out #202. It is sort of a temporary fix, since the query resolvers don't see the defaults yet. Let me know if #202 is what you are looking for or you need the `cache.readQuery` functionality as well.

@wKovacs64 Thank you for the followup! Hopefully I can live up to a clone of peggy :pray: Please take a peek at #202 when you get a chance!

**Comment by wowzaaa** [comment]
@evan hi and thank you for your help ... i added Query: () => {}, to the resolvers but not it triggers a warning that Missing field counter in {}
i updated the codesandbox demo
https://codesandbox.io/s/3q2724orp5

thanks

**Comment by wKovacs64** [comment]
#202 ..._*resolves_... the issue for my use case (I don't need `cache.readQuery` yet). Thank you, @evans!

*~~Sorry, couldn't resist.~~ Not sorry. 😆

**Comment by wowzaaa** [comment]
@wKovacs64 did u do anything else than adding `Query: () => ({}),`  to the resolvers? beucase i suggested that a few days ago and u mentioned the a missing field warning appears ... which i understand you do not get anymore ... so did u change anything else?

thanks

**Comment by wKovacs64** [comment]
@wowzaaa I didn't add `Query: () => ({})`, it works without that (as it should). PR #202 is what fixes it, but it isn't merged/published yet. To test and confirm that it works for you, you can perform the following steps:

1. `git clone https://github.com/apollographql/apollo-link-state.git`
1. `cd apollo-link-state/packages/apollo-link-state && git checkout reset-store-fix`
1. `yarn && yarn build`
1. [`yarn link`](https://yarnpkg.com/lang/en/docs/cli/link/)
1. Change directories back into your project
1. `yarn link apollo-link-state`

At that point, your project will be using your local copy of `apollo-link-state` with the fix in place. 

Note:
If you do this, be sure to [`yarn unlink`](https://yarnpkg.com/en/docs/cli/unlink) when you're done testing.

**Comment by wowzaaa** [comment]
awesoeme response thanks :)

yes it works :)
