### ISSUE TITLE
Using `cache.writeQuery()` on client side state in downstream link does not update `ObservableQuery` observers or `graphql` HOC

### ISSUE THREAD

**Issue by ashutoshrishi** [apollographql/apollo-link-state#200]
I want to set a `isLoading` flag when a mutation starts and reset it when the mutation finishes. This flag is stored in the client side query data initialised using `apollo-link-state` as:

```javascript
const stateLink = withClientState({
  cache: apolloCache,
  defaults: {
    requestStatus: {
      isLoading: false,
    },
  },
})
```

The link chain looks like:

```javascript
  const link = ApolloLink.from([
    errorLoggerLink,
    new RequestTrackerLink(),   // my custom link
    stateLink,
    new HttpLink(options),
  ]);
```

In my custom link `RequestTrackerLink` when the `request(operation, forward)` is called, I use `cache.writeQuery()` (`cache` is from the operation context) to update the Query:

```javascript
  const query = gql`
    query {
      requestStatus {
        isLoading
      }
    }
`;
  const previous = cache.readQuery({ query });
  const data = {
    ...previous,
    requestStatus: {
      ...previous.requestStatus,
      ...newStatus,  /// newStatus is { isLoading: true }
    },
  };
  cache.writeQuery({ query, data });
```

This does not trigger an update in a `graphql(query, ...)` component else where watching the query:

```
  const query = gql`
    query {
      requestStatus @client {
        isLoading
      }
    }
`;
```

Am I use `writeQuery` with the `cache` from `const { cache } = operation.getContext()` incorrectly?

**Comment by ashutoshrishi** [comment]
The `callback()` for the query in `cache.watches` is called with the updated result. That makes the query in the `client.queryManager.queries` update with `newData` and become `invalidated`:

```javascript
{
listeners: [ ..1 listener.. ],
invalidated: true,
newData: {
  complete: true,
  result: {
     requestStatus: { ... }
  }
}
}
```

This is the callback code given to the cache:

https://github.com/apollographql/apollo-client/blob/3585430d666c331fd7392e4b4d36fd2ed15b410f/packages/apollo-client/src/core/QueryManager.ts#L736-L744

But the `listeners` for that query in the QueryManger  is never called. 

So if I use `client.writeData(...)` (client is the ApolloClient instance) instead of the `cache.writeData(...)` (cache is the InMemoryCache instance obtained from the operation context, everything works because `client.queryManager.broadcastQueries()` is called.

**Comment by mjasnikovs** [comment]
I had the same problem. And "fixed" by importing apollo client and running writeData on it, instead of context attached cache object. Does not feels the right way of doing this.

**Comment by fbartho** [comment]
As I understand it, if you want "side-effects" you need to execute against the ApolloClient like @mjasnikovs suggested. The cache is a data-store, it's not intended to be directly observed. (Otherwise it would be really easy to have infinite loops!).

I don't know how long mutations take for you, but you may want to consider the `Mutation` component in React-Apollo instead!

I'm going to close this issue as there doesn't appear to be actions that the implementing team has here. Feel free to open a feature request if you think some behavior should be changed.
