### ISSUE TITLE
including locks files in the repo

### ISSUE THREAD

**Issue by akiran** [apollographql/apollo-link-state#201]
Some times tests are failing in my local repo which I use for development because of package version mismatch.

These problems can be solved by including lock files in the repo

**Comment by peggyrayzis** [comment]
Unfortunately, there are still no best practices for using lockfiles with Lerna. None of our other Lerna repos have lockfiles, so I'm going to leave it out for consistency.

Occasionally, you should run `npm run bootstrap` from the root to make sure your packages are up to date.
