### ISSUE TITLE
How to reset variable in state on unmount or another action

### ISSUE THREAD

**Issue by kavink** [apollographql/apollo-link-state#204]
What is recommended way to reset the state either when component is removed from screen or on clicking ```X```

**Comment by fbartho** [comment]
@kavink -- This is really a great question -- unfortunately, it's really specific to your application. I probably would recommend you ask this on StackOverflow or in Slack as people can give you their opinion there.

Also, I don't know what "reset the state" and "when component is removed from screen" exactly. Those would be helpful to clarify when you ask your questions there.
