### ISSUE TITLE
Local state query re-updates component with no necessity

### ISSUE THREAD

**Issue by ostrebler** [apollographql/apollo-link-state#207]
Hi

I have this code where I simply fetch the `loggedIn` info from the local state : 

```
const sessionQuery = gql`
  query {
    session @client {
      loggedIn
    }
  }
`

export default graphql(sessionQuery, { name: 'localState' })(
  ({ localState: { session }}) => {
    console.log('rendering App with session:', session)
    return !session.loggedIn ?
      <Logger/>
    : [
      <Grid key={0}>
        <Actions/>
        <Authors/>
      </Grid>,
      <Grid key={1}>
        { Array.from(Array(16).keys()).map(
            shelf =>
              <Shelf key={ shelf + 1 } shelf={ shelf + 1 }/>
          )
        }
      </Grid>
    ]
  }
)

```

Even if the query data is fully available on first render, somehow an update and second render is triggered. This logs with a few ms delay : 

```
rendering App with session: {loggedIn: true, __typename: "Session", Symbol(id): "$ROOT_QUERY.session"}
rendering App with session: {loggedIn: true, __typename: "Session", Symbol(id): "$ROOT_QUERY.session"}
```

Why is that ?

Also, I noticed sometimes the data from the local state is available immediatly, sometimes it's not (right after mutations ?). I suggest you clarify that behaviour in the doc.

Thanks a lot
Olivier

**Comment by johnunclesam** [comment]
@ostrebler, maybe the same question? https://github.com/apollographql/apollo-link-state/issues/217

**Comment by peggyrayzis** [comment]
This is a `react-apollo` issue, not `apollo-link-state`. Discussion has been opened up on the `react-apollo` repo:
https://github.com/apollographql/react-apollo/issues/1777

Thanks! 😀
