### ISSUE TITLE
Automagically subscribe all fetched items and keep it in sync with the server?

### ISSUE THREAD

**Issue by coodoo** [apollographql/apollo-link-state#208]
Is it possible to setup subscriptions for all cached items so that whenever any of those items was changed on the server, it will be updated on the local too?

**Comment by walshie4** [comment]
This sounds outside the scope of `apollo-link-state`, may want to look into something like Firebase (https://firebase.google.com/)

**Comment by walshie4** [comment]
or possibly #138
