### ISSUE TITLE
Mutation for both local and remote data?

### ISSUE THREAD

**Issue by coodoo** [apollographql/apollo-link-state#209]
I'm wondering what's the best practice for following scenario:

If an item was cached locally and user changes it's value, should I issue two mutations (one against the remote server, one to the local cache), or I just need to send mutations to the remote server and the local one will be updated in sync?

**Comment by peggyrayzis** [comment]
Hi @coodoo! `apollo-link-state` mutations are not sent to the server. This is an example of a remote mutation, which is always sent to the server first. Depending on the mutation, you may or may not need to [update the cache](https://www.apollographql.com/docs/react/essentials/mutations.html#update) via the `update` function.
