### ISSUE TITLE
Propose Making Slight Change to the Block of Code in State Link Initialization Section

### ISSUE THREAD

**Issue by jaimemendozadev** [apollographql/apollo-link-state#212]
The original block of code in the State Link Initialization section reads: 

```
const stateLink = withClientState({
  cache,
  resolvers: {
    Mutation: {
      /* same as above */
    },
  },
  defaults: {
    networkStatus: {
      __typename: 'NetworkStatus',
      isConnected: true,
    }
  },
});
```

I propose changing the code section to reflect as follows for readability and clarity. Mostly it's based from watching the Sara Vieira `apollo-link-state` video one too many times and getting accustomed to seeing `defaultState` being initialized like so:

```
const defaultState = {
  networkStatus: {
    __typename: 'NetworkStatus',
    isConnected: true,
  }
};

const stateLink = withClientState({
  cache,
  resolvers: {
    Mutation: {
      /* same as above */
    },
  },
  defaults: defaultState,
});
```

I already made the change in my fork of the repo. Let me know what you guys think.

**Comment by peggyrayzis** [comment]
Hi @jaimemendozadev! Thanks for your feedback. I'm not convinced that pulling `defaultState` into its own variable is an improvement on readability. I'd prefer if people split `defaults` and `resolvers` into their own modules if they didn't want to inline their defaults during setup. I'm going to close this for now, but if enough people support the change, then I will reconsider. 😀

**Comment by jaimemendozadev** [comment]
Hey @peggyrayzis! Totally understand. Thank you for looking at the issue. 😄 Btw, big fan of the work you and the Apollo Team do, particularly your Medium articles or YouTube videos. Please keep it up! 👍 🚀
