### ISSUE TITLE
Calculate computed state

### ISSUE THREAD

**Issue by klis87** [apollographql/apollo-link-state#213]
Is there any way to achieve with this library something similar to Redux reselect or Mobx computed? Deriving from state outside of components is really crucial for any state management system. I am asking because this will answer whether I can totally give up Redux/Mobx in Apollo apps. 

1 idea I have is to do it via HOC, but maybe you have some better ideas?
```js
import React, { Component } from 'react';
import gql from 'graphql-tag';
import { graphql } from 'react-apollo';

const query = gql`
  query user {
    user @client {
      username
    }
  }
`;

const withUserIsAuthenticated = WrapperComponent => {
  @graphql(query)
  class WithUserIsAuthenticated extends Component {
    render() {
      const { data: { user }, ...rest } = this.props;
      const isAuthenticated = !!user.username;
      return <WrapperComponent isAuthenticated={isAuthenticated} {...rest} />;
    }
  }

  return WithUserIsAuthenticated;
};
```

**Comment by peggyrayzis** [comment]
Hi @klis87! With Apollo Client, your GraphQL queries are your selectors. If you find that you're using derived state often in your components, why not add the `isAuthenticated` property to the User type?

**Comment by klis87** [comment]
@peggyrayzis good point! So here is a thing which came to my mind. Lets say I fetched unsorted items from graphql server. Now, I need to have sorted version. Do you think that sorting it on client once and then putting it to `@client` mutation is a good idea?

**Comment by peggyrayzis** [comment]
I would move your sorting logic to the server and expose your sorting method as a query parameter. Your GraphQL schema should reflect how you're consuming the data on the client. By moving your sorting logic to the server, you won't have to duplicate it if you have multiple clients consuming your GraphQL API.

**Comment by klis87** [comment]
Good idea. Thanks!

**Comment by gregkerzhner** [comment]
@peggyrayzis I am not sure i understand your answer.  If I have a user field with `firstName` and `lastName` and am looking for a field `fullName` that is `firstName + lastName`, are you saying I should also add the `fullName` to my schema and manually set it whenever `firstName` or `lastName` changes?  That process seems error prone and against the principle of saving the minimum possible state.  Is there any way to have apollo-link-state return transformations / combinations of data thats already in the cache as new fields?
