### ISSUE TITLE
undefined as value?

### ISSUE THREAD

**Issue by gex** [apollographql/apollo-link-state#214]
hello,

i try to save an object to the state:
```js
export default {
  defaults: {
    location: {
      __typename: 'Location',
      pathname: '',
      search: '',
      hash: '',
      state: undefined
    }
  },
  resolvers: {
    Mutation: {
      updateLocation: (obj, { location }, { cache }) => {
        const data = {
          location: {
            __typename: 'Location',
            ...location
          }
        }
        cache.writeData({ data })
        return null
      }
    }
  }
}
```
and i get `Missing field state in...` errors. the `location` object is coming from the [history](https://www.npmjs.com/package/history) package so the only way i can change this behavior is to set the default value to `null` and manually change the variable in the resolver function.

is it possible to use `undefined` as a value in the state?

**Comment by peggyrayzis** [comment]
Hi @gex! You have to use null since all GraphQL types are nullable by default. Since this is the intended behavior, I'm going to close this issue.
