### ISSUE TITLE
Mutation or writeQuery or writeData from index.js (like Redux store.dispatch()).

### ISSUE THREAD

**Issue by johnunclesam** [apollographql/apollo-link-state#216]
I have this code in my index.js:

```
...
const token = localStorage.getItem("myToken");
if (token) {
  store.dispatch({ type: USER_LOGGED_IN });
}

ReactDOM.render(
  <ApolloProvider store={store} client={client}>
     <App />
  </ApolloProvider>,
  document.getElementById("root")
);
...
```

how to do with apollo-link-state?

I have to use `graphql(MUTATION_GQL)` ?

Or `writeData` directly? I'm stucked.

**Comment by PCreations** [comment]
You can simply use the low level `apollo-client` api to trigger a mutation :
```javascript
client.mutate({
  mutation: MUTATION_GQL,
  variables: { token },
})
```

**Comment by fbartho** [comment]
@johnunclesam -- The solution from @PCreations should work. Or you should investigate [`apollo-link-context`](https://www.apollographql.com/docs/link/links/context.html) to make an Auth Link!
