### ISSUE TITLE
Useless re-rendering of simple components. DEMO.

### ISSUE THREAD

**Issue by johnunclesam** [apollographql/apollo-link-state#217]
This is the console log:
![image](https://user-images.githubusercontent.com/21275217/36942107-65e7f052-1f6b-11e8-887c-457b339e43be.png)

## The reproduction demo is here: https://codesandbox.io/s/8n89yrwjx0

This is the relevant code:

```javascript
const cache = new InMemoryCache();

const stateLink = withClientState({
  cache,
  resolvers: {
    Mutation: {
      updateStatus: (_, { isEnabled }, { cache }) => {
        const data = {
          status: {
            __typename: "status",
            isEnabled
          }
        };
        cache.writeData({ data });
        return null;
      }
    }
  },
  defaults: {
    status: {
      __typename: "status",
      isEnabled: false
    }
  }
});

const client = new ApolloClient({
  link: stateLink,
  cache
});
```

Everytime it re-renders `Hello` component. **Why?**

I noticed in my Chrome console a difference in the "refetch" prop.

But, in any case, also if I use this code:

```javascript
export default graphql(STATUS_QUERY, {
    props: ({ data: { loading, error, isEnabled } }) => {
      if (loading) {
        return { loading };
      }

      if (error) {
        return { error };
      }

      return {
        loading: false,
        isEnabled
      };
    }
  }
)(Hello);
```

it seems to re-render because `props` are different by reference. **Why?**

**Comment by peggyrayzis** [comment]
This is a `react-apollo` issue, not `apollo-link-state`. I see you've opened it up on there too, so I'm going to close this to avoid duplication. Thanks! 😀

**Comment by johnunclesam** [comment]
Ok. I firstly recognized it using link-state... :) Thanks for your work!
