### ISSUE TITLE
PR 202 reproduction on codesandbox, but the problem is another one.

### ISSUE THREAD

**Issue by johnunclesam** [apollographql/apollo-link-state#218]
Unfortunately here: https://codesandbox.io/s/184o5jmxvj I have the PR 202 problem:

![image](https://user-images.githubusercontent.com/21275217/36975027-0d1892e2-2079-11e8-96b0-1ea52426af9c.png)

On my local PC I fixed it by downloading master branch in my `node_modules`.

If you release a new version I can show you the real problem:

`MenuAuthenticated` is re-rendered after `signIn` (after updating with `link-state`) but it doesn't use `localStorage` token for server query (`CURRENT_USER`).

Can you release `0.4.1`, please (I don't think on codesandbox I can upload my personal `node_modules` folder) so I can show you the problem.

**Comment by peggyrayzis** [comment]
0.4.1 is released, can you please open another issue if you are still experiencing a problem?
