### ISSUE TITLE
Mixed client/remote queries not hitting client query resolvers on cache misses

### ISSUE THREAD

**Issue by Jannis** [apollographql/apollo-link-state#221]
The issue requires Apollo Client to be set up as follows (no client state `defaults`, two client-side query resolvers):
```js
var cache = new InMemoryCache()

var stateLink = withClientState({
  cache,
  resolvers: {
    Query: {
      example: () => {
        console.log('Simple query cache miss')
        return true
      },
      isSelected: () => {
        console.log('Mixed query cache miss')
        return true
      }
    }
  },
})

var httpLink = new HttpLink({
  uri: 'https://mpjk0plp9.lp.gql.zone/graphql'
})

var client = new ApolloClient({
  link: ApolloLink.from([stateLink, httpLink]),
  cache
})
```

Since there is no default state, any query using the `@client` derivative should be a cache miss and thus result in the corresponding query resolver to be called.

This works fine with simple mixed client/remote queries like this one:
```graphql
{
  droid(id: "2000") {
    id
    name
  }
  example @client
}
```
which successfully logs `Simple query cache miss` when executed.

However, more advanced queries like the following currently fail to result in a cache miss and the `isSelected` resolver is never called:
```graphql
{
  droid(id: "2000") {
    id
    name
    isSelected @client
  }
}
```
Instead, the query fails with the following error: `"Network error: Cannot read property 'isSelected' of undefined"`.

Defining `defaults: { isSelected: true }` in the client state makes the query succeed, but obviously the client-side resolver for `isSelected` is never called because there is something in the cache already.

Defining empty defaults yields yet another query result: `null`.

I have created a CodeSandbox example demonstrating the problem: https://codesandbox.io/s/qq11361w3w?module=%2Fsrc%2Findex.js.

Note: I'm aware that this issue may have its root cause in one of the other Apollo libraries but I'm filing it here initially, since I don't know how responsibilities are divided between them.

**Comment by akiran** [comment]
@peggyrayzis @evans  
I tested this and adding @client on nested fields is not working 

This works
```
 user {
    id
 }
 isLoggedin @client
```

But this doesn't work
``` 
{
    user {
        id
        isLoggedin @client
    }
}
```

Nested @client directive used to work in my branch with this logic
https://github.com/akiran/apollo-link-state/blob/6a785eb095180370187efb2592cd11cfa2d1625e/packages/apollo-link-state/src/index.ts#L95-L99
But, that logic is removed in the release

**Comment by peggyrayzis** [comment]
Hi @Jannis! Your `isSelected` resolver should be on the `Droid` type, not the `Query` type since it is a part of the Droid selection set. Here's what that should look like [in your sandbox](https://codesandbox.io/s/32w9xwk9n5).

You can also see an example of adding a client field to server data in [Pupstagram](https://codesandbox.io/s/r5qp83z0yq). In that example, we're adding the `isLiked` field to the `Image` type returned from the server.

Hope this helps! 😀

**Comment by Jannis** [comment]
Perfect @peggyrayzis, thanks. I hadn't seen an example of anything other than `Mutate` for apollo-link-state yet. Now I'm not even sure how I thought putting this on `Query`made any sense in the first place.

Thanks a bunch for updating the sandbox and the Pustagram pointer!

**Comment by brunobasto** [comment]
Agreed. Some more docs / examples on querying could be nice.

Thanks for all your work. This module is awesome!

**Comment by aethernet** [comment]
This absolutely needs to be more explicit in the documentation! Took me close to a day of research to get to this post... A couple hours ago I was sure it was a bug in one of the libs...
