### ISSUE TITLE
tree of local resolvers in client and server mixed queries

### ISSUE THREAD

**Issue by akiran** [apollographql/apollo-link-state#223]
In the pupstagram demo, isLiked resolver in Images is executed. But it parents resolvers i.e images and dog are not executed
I made a fork of pupstagram to demostrate this 
https://codesandbox.io/s/q4kz4v985q

Should we support resolver execution of entire tree starting from query similar to server ?

One drawback of executing only leaf resolvers is that it won't have access to variables of parent fields
```
const GET_DOG = gql`
  query getDogByBreed($breed: String!) {
    dog(breed: $breed) {
      images {
        url
        id
        isLiked @client
      }
    }
  }
`;
```
In this case, variables passed to isLiked resolver is null and it didn't have access to breed variable

**Comment by fbartho** [comment]
As I understand i, if you want to access the variables, you should specifically pass them in:

```
const GET_DOG = gql`
  query getDogByBreed($breed: String!) {
    dog(breed: $breed) {
      images {
        url
        id
        isLiked(breed: $breed) @client
      }
    }
  }
`;
```

It's perhaps suboptimal, but that's how I understand how it should work today.

**Comment by peggyrayzis** [comment]
This behavior is consistent with what happens on the server. If you look at this [launchpad](https://launchpad.graphql.com/8v9j5zkzrq), click on Logs, and run the query, you'll notice that the images resolver doesn't get the arguments passed to the dog resolver. If you want to access those arguments, you'll have to pass them yourself like in @fbartho's example.
