### ISSUE TITLE
How to access local state in own Query resolver function?

### ISSUE THREAD

**Issue by nilshartmann** [apollographql/apollo-link-state#225]
Hi,

I have client State that consists of a list of items. Now I'm trying to implement an own Query resolver, that should return exactly one of the items in the list, that is identified by an argument passed (like `getItemByXyz(xyz: ...)`).

While my resolver is called with the correct argument from the query, I have no idea how to get the current state (my array of items) in the resolver implementation, so that I could find and return the queried item.

```
const client = new ApolloClient({
  uri: "http://localhost:3000/graphql",
  clientState: {
    defaults: {
      draftMessages: [],
     . . .
    },
    resolvers: {
      Query: {
        getDraftMessageById: (_, { draftMessageId }, { cache }) => {
         // how to get the current list of draftMessages here?
      },
      Mutation: {
        addDraftMessage: (. . .) => { }
     }
});
```

I think this would be very similiar to adding a `getTodoWithId(todoId: ...)` Query in your todo example app (https://github.com/apollographql/apollo-link-state/blob/master/examples/todo/src/resolvers/todos.js)

Can you point me to docs/example how I could implement such a resolver? 

Thanks a lot!

---
Maybe related: In the docs on Resolvers (https://www.apollographql.com/docs/link/links/state.html#default) it says `For this query, you will need to specify a resolver for Query.user in your resolver map` but unfortunately there is no example how one would implement this specific user resolver...

**Comment by PCreations** [comment]
You can use the `cache.readFragment` method to query a specific item in the cache (given that this item is already in the cache, wheter by setting the defaults value or because it was added via mutation) :

```javascript
const client = new ApolloClient({
  uri: "http://localhost:3000/graphql",
  clientState: {
    defaults: {
      draftMessages: [{
        id: '1',
        content: 'message 1',
        __typename: 'DraftMessage',
      }, {
        id: '2',
        content: 'message 2',
        __typename: 'DraftMessage',
      }],
    },
    resolvers: {
      Query: {
        getDraftMessageById: (_, { draftMessageId }, { cache }) => {
          const fragment = gql`
            fragment draftMessage on DraftMessage {
              content
            }
          `
          /*
          If you haven't edited the dataObjectFromId config property of your cache instance, the cache id
          is the following as stated in the docs :
          https://www.apollographql.com/docs/link/links/state.html#write-fragment
          */
          const id = `DraftMessage:${draftMessageId}`;
          return cache.readFragment({ fragment, id })
      },
      Mutation: {
        addDraftMessage: (. . .) => { }
     }
});
```

I think this issue is best suited for StackOverflow, maybe you should move your question here to make it more visible for other people struggling with this !

**Comment by nilshartmann** [comment]
Hi,

thanks for your reply, that works! 👍

To get the actual list of draft messages from the local cache (for example to filter by other criterias than the `id`), I wrote in my resolver:

```javascript
resolvers: {
  Query: {
    getDraftMessageById: (_, { draftMessageId }, { cache }) => {
      const allDraftMessagesFromCache = cache.readQuery({
        query: gql`
        query getDraftMessages @client {
          draftMessages {
            id
            text
          }
        }`
   });

   return allDraftMessagesFromCache.find(. . .);
  }
}
```

Is that correct?

**Comment by PCreations** [comment]
Sure, it might work !

**Comment by fbartho** [comment]
Closing issue as resolved!
