### ISSUE TITLE
Store gets reset on every update

### ISSUE THREAD

**Issue by rivertam** [apollographql/apollo-link-state#228]
So I've got this problem where I'll update the cache using a mutation (practically example code) and the query will refresh with the defaults.

I've extracted the relevant code below.

Link code:

```javascript
import { isArray, cloneDeep } from 'lodash/fp';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { withClientState } from 'apollo-link-state';
import { QueryAllSubscriptionSets } from '../GraphQL/Debug';

const cache = new InMemoryCache();

const resolvers = {
  Mutation: {
      console.log('mutate');
      let set = {
        __typename: 'SubscriptionSet',
        name,
        subscriptions,
      };

      const { subscriptionSets: sets } = cache.readQuery({
        query: QueryAllSubscriptionSets,
      });

      const extantSet = sets.find(set => set.name === name);
      if (extantSet) {
        extantSet.subscriptions = subscriptions;
        set = extantSet;
      } else {
        sets.push(set);
      }

      cache.writeData({
        data: {
          subscriptionSets: sets,
        },
      });

      return set;
    },
  },
};

export default withClientState({
  cache,
  resolvers,
  defaults: {
    // can't make it an object because then we can't query by all fields
    subscriptionSets: [],
  },
});
```

Query:

```javascript
import gql from 'graphql-tag';

export const MutationStoreSubscriptionSet = gql`
  mutation StoreSubscriptionSet(
    $name: String!
    $subscriptions: SubscriptionSet!
  ) {
    storeSubscriptionSet(name: $name, subscriptions: $subscriptions) @client
  }
`;

export const QueryAllSubscriptionSets = gql`
  query GetAllSubscriptionSets {
    subscriptionSets @client {
      name
      subscriptions
    }
  }
`;
```

compose:

```javascript

export default compose(
  graphql(MutationStoreSubscriptionSet, {
    props: props => ({
      storeSubscriptionSet: (name, subscriptions) => {
        console.log('a', name, subscriptions);
        return props.mutate({
          variables: { name, subscriptions },
        });
      },
    }),
    options: () => ({
      refetchQueries: [{ query: QueryAllSubscriptionSets }],
    }),
  }),
  graphql(QueryAllSubscriptionSets, {
    props: props => {
      console.log('b', props);
      return { subscriptionSets: props.data.subscriptionSets || [] };
    },
  }),
)(MyComponent);
```

So what happens when I call `storeSubscriptionSet` is the console prints "a" along with the relevant parameters. Then "b" gets printed once with `loading: true`, once with `loading: false` and the `subscriptionSets` set to an array of length 1 (which is good), and then once again with `loading: false` and `subscriptionSets` set to an empty array. The mutation isn't called multiple times: "mutate" and "a" are only printed once, at the appropriate times.

I'm kind of at my wit's end here. I don't even know why the query is being called again, much less why the cache is being emptied.

Can anyone help?

**Comment by rivertam** [comment]
Initially, I thought it might be because I was using multiple caches (one for my full application and one for my local state). I would prefer to do this, but I recognize it's not the typical way and may have issues, so I restructured it so I'd use the same cache for both, but I'm still running into the same issue.

**Comment by rivertam** [comment]
Hmmm... I took out the `refetchQueries` and now it's not clearing (thought it is auto-updating). This doesn't make any sense to me. Looking internally in the cache with the `refetchQueries` in, the cache actually does get cleared. However, when I take it out, the cache does not get cleared. I'm assuming this is some kind of behavior relevant to networked GraphQL ("refetch" I guess means clear cache before fetching again), but I don't think this should have this behavior in this case... Honestly, it seems like a fundamental flaw with the idea of using the cache as a state store, as opposed to a separate backing store like Redux.

**Comment by peggyrayzis** [comment]
Hi @rivertam! This is the intended behavior. You don't need to call `refetchQueries` on client-side mutations. Under the hood, `cache.writeData` writes a query to the cache with the shape of the data that you pass in, so your query is already updated.

**Comment by rivertam** [comment]
@peggyrayzis Got it, thank you. I was under the impression `refetchQueries` also made it so the HOC would rerender with the new values.
