### ISSUE TITLE
Data sharing among components

### ISSUE THREAD

**Issue by gauravmakkar** [apollographql/apollo-link-state#229]
I want to share an object among a number of components(Using @client)
Component 1 is fetching the data using query.
Component 2 is able to mutate the object using custom resolvers.
Component 3 is fetching the data object using query.

The problem is when I mutate the object component 1 and 3 are not aware of data mutation. Am I using the right approach?

**Comment by peggyrayzis** [comment]
Hi @gauravmakkar! 1 and 3 should automatically update as long as you're calling `cache.writeData` with the updated object. Can you please post a reproduction on [CodeSandbox](https://codesandbox.io/) of your issue?

**Comment by hwillson** [comment]
We haven't heard back regarding the additional information requested in https://github.com/apollographql/apollo-link-state/issues/229#issuecomment-376152330, so closing for now. Thanks!
