### ISSUE TITLE
Can non GraphQL clients use ApolloLinkState?

### ISSUE THREAD

**Issue by cliren** [apollographql/apollo-link-state#238]
We don’t have any GraphQL API as of now but we plan to have it in the near future. On a brand-new React Native new client project, is ApolloLinkState a good choice instead of redux and does it work with out any Apollo GraphQL dependency?

**Comment by fbartho** [comment]
Technically speaking, you could use `apollo-link-state` directly, but that's really not the intended use-case @cliren. All of the documentation and structure is optimized for building a chain of `apollo-link`s that are dispatched to from `ApolloClient`.

I wouldn't recommend using ApolloLinkState without GraphQL in my opinion.

**Comment by peggyrayzis** [comment]
Hey @cliren! Apollo Link State isn't super useful without the client. You can use Apollo Link State and Apollo Client without a GraphQL server to manage just your local state if you'd like. You can also use [`apollo-link-rest`](https://www.apollographql.com/docs/link/links/rest.html), which will allow you to query your REST endpoints with GraphQL, as a temporary solution until you're ready to build out your GraphQL server. Both are suitable Redux replacements. Hope that helps!

**Comment by cliren** [comment]
We don't want to end up two state managers on the client side. Your suggestion sounds great with apollo-link-rest, will give it a try and see how it works. Thanks @peggyrayzis!
