### ISSUE TITLE
Defaults for array of objects

### ISSUE THREAD

**Issue by actuallydan** [apollographql/apollo-link-state#242]
For my app, I'm getting a bunch of user data remotely when they sign in, and then saving it in the cache but I'm getting this issue: 
```
Uncaught Error: Encountered a sub-selection on the query, but the store doesn't have an object reference. This should never happen during normal use unless you have custom code that is directly manipulating the store; please file an issue.
    at assertIdValue (readFromStore.js:135)
```

**Intended Outcome**
Cache is updated, and it doesn't throw exceptions.

**Actual Outcome**
Cache is updated, and @client data is available in DevTools, but it still crashes my browser (components all unmount and I'm left with a blank screen) and forces me to refresh. 

I checked [this issue in apollo-client](https://github.com/apollographql/apollo-client/issues/1415) as it's the only other place I've seen this error on the web, but It looks like a completely different problem.

So if I have a defaults state config that has a field that actually contains an array of objects like this:
```javascript
export const defaults = {
...
circles: {
        __typename: "Circles",
        myCircles: []
    },
....
};
```
and the resolver looks like this: 
```javascript
export const resolvers = {
    Mutation: {
         saveAllData: async (_, { allUserData, allChannels }, { cache }) => {
             try {
                 ...
                 const circles = {
                     __typename: "Circles",
                     myCircles: allUserData.circles
                  };
                 ...
                 await cache.writeData({
                    data: {
                        ...
                        circles
                        ...  
                    }
                  });
                return true;
            } catch (err) {
                console.log(new Error(err));
                return false;
            }}
    },
};
```
I've narrowed the error down to the `cache.writeData` call; I tried writing everything else without the "circles" object and it functions normally, and including it always crashes.

It's understand entirely likely that this is too specific of a problem. I was unable to get a slimmed-down replica working [in codeSandbox](https://codesandbox.io/s/00mx10kyol?module=%2Fsrc%2Fresolvers.js), but even there I'm seeing baffling failure.  I'm just hoping someone has seen something like this or can point out a rookie mistake. 

My best guess is that it's just having a fit with circles.myCircles being an array, but I can't find any documentation that says whether you can/should/how to do this.

I'm fairly certain I'm using the latest packages but specifically: 
apollo-cache-inmemory: "^1.1.12",
apollo-client: "^2.2.8",
apollo-link-state: "^0.4.1",

**Comment by sbrichardson** [comment]
Just a thought- Do you have an id field on all objects and any nested types? Are you removing or updating data later and not including the id field?

**Comment by actuallydan** [comment]
Every object, and also every nested object has an id field. For example, here's what one of the circle objects to be stored looks like:
```javascript
const circle = {
    id: "9as87df98a798sdf",
    name: "ExampleName",
    icon: "aws.something.com/resource.png",
    preamble: "Example Text",
    amendments: [],
    channels: [
        { 
            id: "sd9f87v6s9d87f", 
            name: "testChannel"
        }
     ]
  }
``` 

An array of these objects is what I'm trying to store in the circles.  Every time the data is changed it always has an id.

**Comment by actuallydan** [comment]
After re-visiting the apollo-link-state todo app example, I noticed that arrays in defaults are totally supported and don't need to contain anything (although a __typename is suspiciously absent).

 I'm going to conclude this is just something I'm doing wrong and isn't an issue with link-state or apollo-client.

**Comment by sbrichardson** [comment]
I’ve gotten this error when I try to return a field that’s either not in
the schema, or it’s defined as a JSON field for example, and accidentally
try to add sub field selections.

**Comment by brunorzn** [comment]
We encounter the exact same error, I still haven't found where it could come from... Did you finally fix this @actuallydan  ?

**Comment by actuallydan** [comment]
I wasn't able to fix this.  I ended up not using apollo-link-state.  My best guess at this point is that the data stored in state should be flattened.

My implementation had state looking something like 

```
circles: {
        __typename: "Circles",
        myCircles: [
           {
               id: "9as87df98a798sdf",
               amendments: [
                   <Amendment Objects with unique id>
               ],
               channels: [
                   <Channel Objects with unique id>
               ]
          },
         ...<More Circle Objects>
        ]
    },
```

but maybe should've looked like this:
```
circles: circles: {
        __typename: "Circles",
        myCircles: [Circle],
},
channels: {
        __typename: "Channels",
        myChannels: [Channel],
},
amendments: {
        __typename: "Amendments",
        myCircles:[Amendments]
}
```

I haven't had any time to test it so it's just a hypothesis. I haven't seen anyone else reference this error since I closed the error.

I wish I could be more helpful.

**Comment by jwdinker** [comment]
I have tried to fix this issue as well for 2 days....no idea what the issue is....its out of the box too.

**Comment by justinpincar** [comment]
I'm still inexperienced with Apollo so not sure if I'm doing this correctly, but I fixed a similar error by adding `__typename` to each layer - see this minimal hardcoded example. I'm using `uuid` as `id` but that shouldn't make a difference.

Loving Apollo so far but the `apollo-link-state` docs need a little work.

```
  resolvers: {
    Mutation: {
      updateQuotes: (parent, variables, { cache }) => {
        const { uuid } = variables;
        const id = uuid;
        const fragment = gql`
          fragment quoteStatus on ActiveApplication {
            quoteStatus {
              quotes {
                ask
                term
                rate
                prepayment
                fees
                message
              }
            }
          }
        `;
        const data = {
          __typename: 'ActiveApplication',
          quoteStatus: {
            __typename: 'QuoteStatus',
            quotes: [{
              __typename: 'ApplicationQuote',
              uuid: 'myQuote',
              ask: 134000,
              term: '20year',
              rate: 6.5,
              prepayment: '',
              fees: '',
              message: '',
            }],
          },
        };
        cache.writeFragment({ fragment, id, data });
        return null;
      },
  },
```

**Comment by JacobT14** [comment]
What if we want the default state to be empty, and not filled with default values? We want it to be populated from an api call rather than fake dummy data at the beginning.

**Comment by killjoy2013** [comment]
We're about to start a new project. Considering apollo-link-state for client side state management.  However, what I've read above discouraged me. Do you have any news from Apollo side about fixing these issues? A version upgrade for apollo-link-state maybe? 
Thanks

**Comment by ribas1a3** [comment]
I'm running into the same issue where I have an array of nested array objects and used to work fine, for the most part, that is until I start manipulating the contents of the cache with writeData the local cache starts acting up. Hope I get a solution else would have to try to normalize the arrays and rewrite a fair bit of my code.

**Comment by isabirahmed** [comment]
Alright, guys after spending a couple of days and all possible outcomes, my colleague and I have cracked this. So in our case, the nested array was not being deserialized and was being added as a json type. In order to change this all we had to do finally was just use apolloClient.writeQuery() instead of apolloClient.writeData. Hopefully, this helps someone in the future.

**Comment by iamstratos** [comment]
Check the one above, it worked for me:
https://stackoverflow.com/questions/53355476/storing-arrays-of-data-in-apollo-link-state

**Comment by colinphillips67** [comment]
> Alright, guys after spending a couple of days and all possible outcomes, my colleague and I have cracked this. So in our case, the nested array was not being deserialized and was being added as a json type. In order to change this all we had to do finally was just use apolloClient.writeQuery() instead of apolloClient.writeData. Hopefully, this helps someone in the future.

This worked for me as well.

From the docs:
"To write the data to the cache, you can use either cache.writeQuery or cache.writeData. The only difference between the two is that cache.writeQuery requires that you pass in a query to validate that the shape of the data you're writing to the cache is the same as the shape of the data required by the query. Under the hood, cache.writeData automatically constructs a query from the data object you pass in and calls cache.writeQuery."

It appears that when writeData attempts to construct the query from the shape of the data it doesn't work for nested arrays.
