### ISSUE TITLE
Update local state in response to query ?

### ISSUE THREAD

**Issue by BerndWessels** [apollographql/apollo-link-state#245]
Hi

Imagine I query a list of `accounts`.
Now when the query result comes back from the server I want the local state variable `SelectedAccount` to be set to the first account in the list.

What is the right way to do this?

**Comment by hwillson** [comment]
There are several different ways you can handle this. One approach - after the `accounts` query has completed, you could call [`readQuery`](https://www.apollographql.com/docs/link/links/state.html#write-query) to get the loaded list, grab the first item, then write it to the cache as `SelectedAccount` using [`writeData`](https://www.apollographql.com/docs/link/links/state.html#write-query).
