### ISSUE TITLE
Memory leak - withClientState 'defaults' argument

### ISSUE THREAD

**Issue by devways** [apollographql/apollo-link-state#248]
Hello, I have noticed a very important memory leak problem when using the 'withClientState' function. This memory leak is obviously due to the 'defaults' variable passed to it. The issue seems to come from the function 'withClientState', for there are no leaks anymore once  'cache,writeData({data:default})' is removed from the code. I hope I have given you enough details so that a solution or explanation can be found.

**Comment by brunorzn** [comment]
It was actually a problem with apollo-utilities package, not apollo-link-state directly, see https://github.com/apollographql/apollo-client/pull/3444
