### ISSUE TITLE
Missing field in resolvers

### ISSUE THREAD

**Issue by serranoarevalo** [apollographql/apollo-link-state#250]
So I'm trying to update the cache with a mutation that's on the client but I'm getting very weird errors:

```Missing field logUserIn in { token: ... }```
```Missing field __typename in { token: ... }```

Query:
````ts
export const LOG_USER_IN = gql`
  mutation logUserIn($token: String!) {
    logUserIn(token: $token) @client
  }
`;
````
Mutation:

````ts
logUserIn: (
    { parent }: { parent: any },
    { token }: { token: string },
    { cache }: { cache: ApolloCache<any> }
) => {
    // localStorage.setItem("jwt", token);
    const data = {
        user: { __typename: "User", isLoggedIn: true, token }
    };
    cache.writeData({ data });
    return null;
}
````
Trigger

````ts
proxy.writeQuery({
    data: {
        token: facebookConnect.token
    },
    query: LOG_USER_IN
});
````

**Comment by hwillson** [comment]
Any chance you'd be able to put together a small runnable reproduction that shows this happening?

**Comment by hwillson** [comment]
We'll re-open this if you're able to provide a small runnable reproduction. Thanks!
