### ISSUE TITLE
Local queries with parameters don't work (codesandbox.io example included)

### ISSUE THREAD

**Issue by webberwang** [apollographql/apollo-link-state#252]
Local queries with parameters don't seem to work.

```javascript
const GET_TODOS = gql`
  query getTodos($id: ID!) {
    todos(id: $id) @client {  
      id
      text
    }
  }
`;
```

https://codesandbox.io/s/j4mo8qpmrw

https://www.apollographql.com/docs/link/links/state.html#default

**Comment by ofersadgat** [comment]
your codesanbox works for me....unless im missing something

**Comment by hwillson** [comment]
As mentioned in https://github.com/apollographql/apollo-link-state/issues/252#issuecomment-394067456, your reproduction seems to show that parameters are working properly. Let us know if we're missing something (and THANK YOU for including a reproduction! 🙂).
