### ISSUE TITLE
Getting undefined on some of the type resolvers

### ISSUE THREAD

**Issue by ralphchristianeclipse** [apollographql/apollo-link-state#271]
I need to do this just to make things but if not

i got a  cannot read <property> undefined
Error sending the query 'users' TypeError: Cannot read property 'test' of undefined
any ideas? 
```js
  User: {
    email: ({ email = '' }) => email,
    firstName: ({ first_name = '' }) => first_name,
    lastName: ({ last_name = '' }) => last_name,
    zipCode: ({ zip_code = '' }) => zip_code,
    contactNo: ({ contact_no = '' }) => contact_no,
    address: ({ address = '' }) => address,
    city: ({ city = '' }) => city,
    state: ({ state = '' }) => state,
  },
```

**Comment by hwillson** [comment]
We'll need to see more code to be able to help (for example, where are you referencing the `test` property the error message is referring to?). Please post back with either more sample code, or ideally a small runnable reproduction that shows this error. Thanks!
