### ISSUE TITLE
query remains watched in cache after unmounting the wrapped component

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#28]
After unmounting a component wrapped with a query, the query remains watched in `InMemoryCache`. It leads to a major performance issue since writing to the cache (and so broadcasting watches) takes more and more time after each component mounting/unmounting.

To reproduce this you can just mount and then unmount many times a component wrapped with any QraphQL query and look at `this.watches.length` in `InMemoryCache` object.

**Version**

* apollo-client@2.0.0-rc.3
* react-apollo@1.4.16

**Comment by jbaxleyiii** [comment]
➤ James Baxley commented:

@jay1337 can you also try the newest rc (rc.4?)

**Comment by jbaxleyiii** [comment]
➤ jay1337 commented:

@jbaxleyiii Issue still there with rc.4

**Comment by jbaxleyiii** [comment]
➤ James Baxley commented:

@jay1337 that is actually intentional! Currently the updateQueries and the refetchQueries methods only work if an observable is present for that query. React Apollo has a query recycler which keeps the observable around to make this work. We will be deprecating those methods after the 2.0 launch so this can all be removed in the 3.0 because using the plain update method doesn't require the observable. 

I'll see about making recycling opt in though!

**Comment by jbaxleyiii** [comment]
➤ jay1337 commented:

@jbaxleyiii I understand the recycling trick. But when a query is switched to 'standby' fetchPolicy, then it must be removed from the "broadcast watches" of InMemoryCache. Keep in mind that a "broadcast watch" can be very time consuming if its a big query. And if you mount then unmount many components when a user is using an app it will make the app really unusable after some time.

**Comment by jbaxleyiii** [comment]
➤ stale[bot] commented:

This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!

**Comment by jbaxleyiii** [comment]
➤ jay1337 commented:

Hey !

**Comment by jay1337** [comment]
@jbaxleyiii is it solved ?

**Comment by jbaxleyiii** [comment]
@jay1337 this was moved accidentally from Apollo Client repo
