### ISSUE TITLE
[bug] Uncaught (in promise) Error: Network error ApolloError.js:43

### ISSUE THREAD

**Issue by jmarceli** [apollographql/apollo-link-state#282]
Hi,
Thanks for this great library.

Unfortunatelly there is some issue most probably related to the `apollo-link-state` package and probably it could be resolved by updating `graphql-anywhere` to at least 4.1.9 version [loosely related SO topic](https://stackoverflow.com/questions/50153422/apollo-client-network-error-if-field-is-null).

Here is a sandbox. Go and click on "Mutate" button.

https://codesandbox.io/s/pprlzol2oj

I would expect it to show some JSON.stringified error state inside page content and not:
```
ApolloError.js:43 Uncaught (in promise) Error: Network error: test
    at new ApolloError (ApolloError.js:43)
    at Object.error (QueryManager.js:217)
    at notifySubscription (Observable.js:130)
    at onNotify (Observable.js:161)
    at SubscriptionObserver.error (Observable.js:220)
```
in the browser console.
The error message is taken from my local dev env to show exact line numbers. The sandbox has a similar message if you open a browser console, just line numbers are meaningless (at least for me).

**In order to reproduce this issue it might be required to refresh browser emulator after entering codesandbox link.**

If there is anything that I'm doing wrong in my code I would be happy to know that. I that case sory for wasting your time.

**Comment by hwillson** [comment]
I just tried you repro locally, and everything appears to work properly. Might be a CodeSanbox issue?

![screenshot 2018-10-14 14 07 03](https://user-images.githubusercontent.com/137740/46920312-85c5ce80-cfba-11e8-9a4a-07731a8e04cb.png)

**Comment by jmarceli** [comment]
Hi, sorry for the late reply but I didn't notice your answer.
This problem is still valid.

If you run this example locally, please check the browser console.

![screen shot 2018-10-30 at 14 12 53](https://user-images.githubusercontent.com/4281333/47720335-ee18df00-dc4d-11e8-8748-9c8e79100a06.png)
