### ISSUE TITLE
what is the max size of the cache?

### ISSUE THREAD

**Issue by johannwattzon** [apollographql/apollo-link-state#286]
my app caused the browser snap when it query a big data set.  What is the max size of the cache?

**Comment by hwillson** [comment]
Apollo Link State works with whatever cache you have configured via Apollo Client, so this question is better suited in the [Apollo Client](http://github.com/apollographql/apollo-client) repo. That being said, if you're using Apollo Client's default `InMemoryCache`, then there is currently no maximum set.
