### ISSUE TITLE
Undefined on resolvers

### ISSUE THREAD

**Issue by ralphchristianeclipse** [apollographql/apollo-link-state#287]
```js
User: {
    email: ({ email = '' }) => email,
    firstName: ({ first_name = '' }) => first_name,
    lastName: ({ last_name = '' }) => last_name,
    fullName: ({ first_name = '', last_name = '' }) => `${first_name} ${last_name}`,
    zipCode: ({ zip_code = '' }) => zip_code,
    contactNo: ({ contact_no = '' }) => contact_no,
    address: ({ address = '' }) => address,
    city: ({ city = '' }) => city,
    state: ({ state = '' }) => state,
    items: async ({ id }, args, { loader }) => {
      const results = await loader.load(`users-carts/${id}/cart-items`);
      const items = mapCartItems(results);

      return items;
    },
}
```

i have this code

you can checkout 

```js
email: ({ email = '' }) => email,
```

so if remove that resolver field

it always throws an error that it's undefined and a warning with writeToStore missing field email

any ideas?

**Comment by hwillson** [comment]
This sounds like a case of trying to query for data that doesn't yet exist in your local store. Apollo Link State [defaults](https://www.apollographql.com/docs/link/links/state.html#defaults) should help. If not, please post back with a small runnable reproduction. Thanks!

**Comment by riccoski** [comment]
I've noticed that JS errors within resolvers prevents the data from returning however it doesn't throw
