### ISSUE TITLE
Multiple aliases referencing the same field with different arguments stores the same value for both aliases

### ISSUE THREAD

**Issue by jimmycallin** [apollographql/apollo-link-state#304]
I have a query like this:

```
 query displayAuthors($offset: Int) {
    listAuthors(limit: 25, offset: $offset) {
      previewImage: image(width: 80) {
        url
      }
      formImage: image(width: 240) {
        url
      }
    }
  }
`;
```

`previewImage` and `formImage` should return different URLs based on the width argument. Unfortunately it seems like the cache stores both on the same place, leading to the `previewImage` URL getting returning the `formImage` URL.

Let me know if you need more info.

**Comment by hwillson** [comment]
This doesn't appear to be an `apollo-link-state` issue? If you're able to create a small runnable reproduction that demonstrates this, that would be helpful. If your issue doesn't involve `apollo-link-state` however, I'd suggest opening this issue over in http://github.com/apollographql/apollo-client.
