### ISSUE TITLE
Add unmet peer dependency apollo-link@^1.0.0"

### ISSUE THREAD

**Issue by jelteliekens** [apollographql/apollo-link-state#310]
```warning " > apollo-link-state@0.4.1" has unmet peer dependency "apollo-link@^1.0.0".```

**Comment by fbartho** [comment]
… @jelteliekens these are warnings that you need to add these dependencies to your own `package.json`

**Comment by jelteliekens** [comment]
Ok, thanks. After some research I figured it out as well.
