### ISSUE TITLE
__resolveType resolver doesn't return the correct type returns its own type instead

### ISSUE THREAD

**Issue by ralphchristianeclipse** [apollographql/apollo-link-state#315]
There seems to be an issue on interfaces on apollo link state

instead of me getting a JobSeeker or Employer type it returns a User type instead

here is the snippet of the code
```js
const roles = {
  employers: 'Employer',
  jobseekers: 'JobSeeker'
};


  User: {
    __resolveType: user => roles[user.role],
    name: ({ name = '' }) => name
  },
```

**Comment by hwillson** [comment]
Any chance you provide a small runnable reproduction that demonstrates this?

**Comment by hwillson** [comment]
I see you provided more details in https://github.com/apollographql/apollo-link-state/issues/316. Closing here.
