### ISSUE TITLE
Asynchronous, not blocking cache updates don't seem to trigger a UI update

### ISSUE THREAD

**Issue by parris** [apollographql/apollo-link-state#317]
I'm calling a non-blocking async function from a few different client side mutations. The function gets called, the write gets called, the data seems to make its way into the store; however, the UI ends up not updating. Here's what my code looks like: 

```
const asyncSave = debouce((cache, profileId) => {
  fetchgql(...).then(({ data }) => {
    cache.writeData({ id: `Profile:${profileId}`, data: { ... } });
  });
}, 2000, { trailing: true });

...
Mutations: {
  resolverA: (_, { profileId }, { cache }) => {
    ...
    asyncSave(cache, profileId);
    return null;
  },
  resolverB: (_, { profileId }, { cache }) => {
    ...
    asyncSave(cache, profileId);
    return null;
  }
}
```

So both resolverA and resolverB both call this asyncSave method. Eventually calls stop getting made to asyncSave and 2 seconds later we'll actually call the function. This works, the write works, but after the write, the UI does not update. If I then do something minor in the UI that would trigger a store update, then the update does indeed appear to work.

My guess (without reading the internal apollo code), is that UI updates get triggered after mutations "resolve". However, independent cache updates may not cause re-renders. Is this true? Is there anything else to be done here to make a technique like this work?

**Comment by carllippert** [comment]
@parris  You should include your versions of apollo-cache-inmemory and apollo-client. A lot of changes int those libraries recently that have affected some of what your talking about

**Comment by parris** [comment]
@carllippert here are the versions:
```
   "apollo-cache-inmemory": "^1.2.9",
    "apollo-client": "^2.4.1",
    "apollo-link": "^1.2.2",
    "apollo-link-context": "^1.0.8",
    "apollo-link-http": "^1.5.4",
    "apollo-link-state": "^0.4.1",
    "apollo-local-query": "^0.3.1",
```

I'm upgrading everything now.

**Comment by parris** [comment]
This *could* be better now - it appears to work a bit better but I can't fully test. The upgrades undid some monkey patching I had done to use immutablejs - hoping link state 1.0 helps with this. Should we close or should we wait?

**Comment by smolinari** [comment]
@parris - just FYI. link-state was merged into Apollo client as of 2.5.0 alpha, so there is no stand-alone link-state any more. There won't be a 1.0. It's in 2.5.0. Not sure you knew that from the comment. :)

Scott

**Comment by maxschmeling** [comment]
@smolinari I'm not seeing that... what am I missing? Where was it merged in?

**Comment by smolinari** [comment]
@maxschmeling - Here: https://github.com/apollographql/apollo-client/pull/4155

Scott

**Comment by maxschmeling** [comment]
Thanks @smolinari 

I'm going to upgrade to the alpha and see if it fixes my issues with never being able to read updates to the local state data until the app is reloaded.

**Comment by smolinari** [comment]
@maxschmeling 

That PR hasn't yet been merged, so I wouldn't expect much currently until it is. 

Scott

**Comment by maxschmeling** [comment]
@smolinari the last comment says it's all .currently available in the alpha release. Hopefully that's true.

https://github.com/apollographql/apollo-client/pull/4155#issuecomment-446041242

**Comment by smolinari** [comment]
Hmm.. ok. Then have at it! :smile:

Scott

**Comment by parris** [comment]
I *think* this is resolved - closing!
