### ISSUE TITLE
Accessing local and remote data in the same query

### ISSUE THREAD

**Issue by Velua** [apollographql/apollo-link-state#325]
I'm trying to copy this behaviour in the [Documentation](https://www.apollographql.com/docs/link/links/state.html#combine)

![screenshot at 2018-11-02 14 00 15](https://user-images.githubusercontent.com/8017434/47893253-b60cd880-dea7-11e8-9faa-e173b9aaa5eb.png)

I am able to successfully do this in two queries,

```
const GET_DOGS = gql`
  query dogs {
    dogs {
      id
      name
    }
    liked @client
  }
`;
```

which successfully returns 
![screenshot at 2018-11-02 14 04 14](https://user-images.githubusercontent.com/8017434/47893338-3af7f200-dea8-11e8-98cc-1cac85e0cf0d.png)

`data: dogs: {}, liked:{}`

However, if I moved liked up into the dog query it fails.

```
const GET_DOGS = gql`
  query dogs {
    dogs {
      id
      name
      liked @client 
    }
  }
`;
```

![screenshot at 2018-11-02 14 07 42](https://user-images.githubusercontent.com/8017434/47893432-afcb2c00-dea8-11e8-8b5c-9869549bec7a.png)

What could I be doing wrong? Created a whole new create-react-app just to try troubleshoot this, it's driving me nuts. Tried engaging the GraphQL Slack but it's not sending me a slack invite across 2 emails I put in.

**Comment by Velua** [comment]
Just added 

```
const defaults = {
  liked: {
    __typename: "setting",
    toolbar: true
  }
};
```

Which now makes 

```
const GET_DOGS = gql`
  query dogs {
    dogs {
      id
      name
      liked @client 
    }
  }
`;
```

work! However, now the Query I have in the resolver no longer seems to be engaged? Therefore it's always defaulting to the default data? :confused:

**Comment by Velua** [comment]
Yeah I'm getting the same issue, sucks!

**Comment by Velua** [comment]
I've made a test environment here https://github.com/Velua/apollo-issue
Can offer anyone some crypto if you get this solved!

**Comment by Velua** [comment]
Upon reading those docs, 
> you'll soon be able to request @client data, @rest data, and data from your GraphQL server all in one query!

I'm getting the feeling this is a feature to be released in the future... What do you think @charlie632  ?

**Comment by charlie632** [comment]
Sounds nice! Even though, it seems a little bit contradicting that there's an example of this behaviour on the official docs but no support yet.

**Comment by Velua** [comment]
Got it working on the latest alpha version!
