### ISSUE TITLE
Stupid docs

### ISSUE THREAD

**Issue by daryn-k** [apollographql/apollo-link-state#336]
Unfortunately Apollo is the most stupid thing I ever met. There are so many confusing things... Even docs. Look at this stupid code:

How can you use `cache` variable two times?
```
const stateLink = withClientState({
  cache, // <-- HERE
  resolvers: {
    Mutation: {
      updateNetworkStatus: (_, { isConnected }, { cache }) => { // <-- HERE
        const data = {
          networkStatus: {
            __typename: 'NetworkStatus',
            isConnected
          },
        };
        cache.writeData({ data });
        return null;
      },
    },
  }
});
```

**Comment by benjamn** [comment]
Are you trying to get banned? Because that tone is unacceptable here.

**Comment by smolinari** [comment]
As a beginner (to anything), a person should be quite humble about what might be right or wrong, because no one will get acceptance to suggested changes or their opinions with the kind of tone or attitude you are demonstrating here. 

And please - always only speak for yourself. You are irritated by the docs. You shouldn't assume everyone else is too.

Scott

**Comment by daryn-k** [comment]
Listen, people complain about many bugs. Today I found an another stupid bug, but not only me - https://github.com/apollographql/apollo-client/issues/3639#issuecomment-441465037 If you're representing your library for others, please, be ready to be humble  and to listen all critics!

**Comment by benjamn** [comment]
Why are you so fixated on the "stupidity" of these bugs? Do you not understand how distracting that language is, and how little it makes anyone want to help you?

**Comment by daryn-k** [comment]
Unfortunately, my questions are ignored. The only way to get attention is to open such issues. Pardon. So, who can me explain why do you use `cache` variable two times? It's not even ESLint-friendly. This code just killng me.
