### ISSUE TITLE
Immutable JS Data from apollo

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#34]
Hi, 

We are trying to implement `react-apollo` in our react app :tada:  one of the blocker that we came across is: 

How can I tell the `apollo-client` that I want the data stored into `redux-store` as an immutable object?

So that i can access it in this way:

```javascript
const MyGqlComponent = ({data}) {
   return <div>data.myquery.get('myField')</div>;
}
```

I remember in the previous versions there was a prop called `immutable` available in the `ApolloProvider` that allowed me to do exactly that!

it doesn't seem to be there anymore, any help please

**Comment by jbaxleyiii** [comment]
➤ stale[bot] commented:

This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!

**Comment by jbaxleyiii** [comment]
➤ Fabrizio commented:

Please can someone help with this

**Comment by lifeiscontent** [comment]
@jbaxleyiii did you ever find a solution?

**Comment by lifeiscontent** [comment]
@peggyrayzis any updates here?

**Comment by lifeiscontent** [comment]
I'd like to know if its possible to use immutable.js in apollo.

**Comment by tonyxiao** [comment]
This should be more of an issue with apollo cache rather than apollo link state I imagine.
