### ISSUE TITLE
how to connect the link-state when we already started the createHttp link?

### ISSUE THREAD

**Issue by luizhenriquesoares** [apollographql/apollo-link-state#4]
how to connect the link-state when we already started the createHttp link?

my snipped goes like this
```
const link = createHttpLink ({
   uri: "http://localhost: 4000/graphql",
   link: withClientState(schema),
   credentials: "include"
});
```
```
const client = new ApolloClient ({
   link,
   cache: new InMemoryCache()
});
```

but it still does not work!

**Comment by jbaxleyiii** [comment]
@luizhenriquesoares you can compose links!

```js
```
const http = createHttpLink ({
   uri: "http://localhost: 4000/graphql",
   link: withClientState(schema),
   credentials: "include"
});

const state = withClientState({ /* your code */ });

const link = state.concat(http)
```

**Comment by luizhenriquesoares** [comment]
@jbaxleyiii  thank you, my friend
