### ISSUE TITLE
Support for promises in resolvers

### ISSUE THREAD

**Issue by carinakoo** [apollographql/apollo-link-state#5]
Awesome to get to start playing with this! 

It would be great to be able to return promises from resolvers. My use case is a mutation to user login state, which calls an auth function returning a promise.

I believe this is the associated PR in `graphql-anywhere`: https://github.com/apollographql/graphql-anywhere/pull/51

**Comment by jbaxleyiii** [comment]
@carinakoo for sure! @JakeDawkins is working on that PR in the new location in the AC repo!

If you are anyone want to help I know he would be appreciative

**Comment by carinakoo** [comment]
Great! @JakeDawkins, what kind of help might be useful?

Is there a new PR already in the AC repo?

**Comment by JakeDawkins** [comment]
@carinakoo I'll get one opened in the next couple hours!

**Comment by JakeDawkins** [comment]
[Here](https://github.com/apollographql/apollo-client/pull/2549) is the PR for this! Tests are broken (maybe a known issue) and I haven't yet gotten the chance to drop this into a project to make sure it works.

@carinakoo If you'd like, you could try running the changes locally

**Comment by carinakoo** [comment]
Tested locally and [noted](https://github.com/apollographql/apollo-client/pull/2549#issuecomment-344360636) an error in the `graphql-anywhere` PR.

It appears that the `apollo-link-state` repo may also require a couple changes to support promises and play nicely with the Apollo Client api. In particular, for `refetchQueries` to be called at the right time:
1) Check if the return value from `graphql-anywhere` is a promise
2) Call `observer.next` and `observer.complete` after the promise resolves

**Comment by jbaxleyiii** [comment]
@carinakoo you are totally correct! I'm going to try to work through the graphql-anywhere PR and see about an alpha / beta for it so we can try it out here!

**Comment by jbaxleyiii** [comment]
@carinakoo @JakeDawkins this is supported in the new release! (That I'm cutting today!)
