### ISSUE TITLE
Query from cache makes component render twice

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#52]
**Intended outcome:**

Example app has a `TopComponent`, which executes query. This component has a nested `BottomComponent`, which also executes the same query.

I expect `BottomComponent` to render only once since data is fetched from cache or at least to have some kind of `loading` / `complete` state.

**Actual outcome:**

`TopComponent` executes query. When `loading` prop is false, `BottomComponent` is rendered. It takes query from cache and renders the same component **twice** with the same props.

**How to reproduce the issue:**

The app is as simple as that:

```jsx
// App
const App = () => {
  const networkInterface = createNetworkInterface({
    uri: 'http://admin.localhost:3000/graphql'
  })
  const apolloClient = new ApolloClient({ networkInterface })
  const store = configureStore(apolloClient)

  console.log('render app')

  return (
    <ApolloProvider store={store} client={apolloClient}>
      <TopComponent />
    </ApolloProvider>
  )
}

// TopComponent
const TopComponent = ({ data: { loading, error } }) => {
  console.log('render top component', loading, error)
  if (loading) {
    return <p>loading</p>
  }

  if (!loading && error) {
    return <p>error</p>
  }

  console.log('before render bottom component')
  return (
    <BottomComponent />
  )
}

export default graphql(query)(TopComponent)

// BottomComponent
const BottomComponent = ({ data: { loading, error } }) => {
  console.log('render bottom component', loading, error)

  return (
    <p>bottom component</p>
  )
}

export default graphql(query)(BottomComponent)
```

The result output:

![screen shot 2017-09-06 at 4 07 01 pm](https://user-images.githubusercontent.com/6711845/30113488-8eb08cae-931d-11e7-9bab-5e7b9e5fc8f8.png)

As you can see, `BottomComponent` renders twice with the same props.

**Version**

* apollo-client@1.9.2
* react-apollo@1.4.15

**Comment by jbaxleyiii** [comment]
➤ Paul Myburgh commented:

Yep running into this issue as well it seems. Causing havok trying to get CSS-in-JS styles working with fela - as the style renderer creates different stylesheets on each render now which collide with each other and the styles get all muddled.

I'm pretty sure this is also related to the previous issue I created #996 , where I noticed two renders being enacted on both server and client.

I uploaded an example project that shows it happening, here: https://github.com/lostpebble/apollo-two-render

**Comment by jbaxleyiii** [comment]
➤ stale[bot] commented:

This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!

**Comment by jbaxleyiii** [comment]
➤ Vlad Shcherbin commented:

What a useless bot, wow. What activity do you expect, it's an issue tracker, not a chat room.

**Comment by jbaxleyiii** [comment]
➤ stale[bot] commented:

This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!

**Comment by jbaxleyiii** [comment]
➤ Jean-François Ducarroz commented:

I am experiencing the same issue!

Looks like GraphQL subscribes to the query on GraphQL.componentDidMount which will force a render once the subscription returns data (via next). This despite it already got the query result when calling GraphQL.dataForChild during the initial GraphQL.render.

**Comment by dineshviveck** [comment]
Facing same issues, React-apollo query wrapper render the components two times
