### ISSUE TITLE
Server rendering causing two renders on each side (twice on server, twice on client)

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#54]
**Intended outcome:**

I would like for my React app to render once on either side. Once on the server, get the state -> hydrate on client and render once.

It could end up causing quite a performance hit if I am essentially rendering my app 4 times for every request.

**Actual outcome:**

I've set up a simple `console.log("Rendering App")` in my `App` render method. It shows that while the server is serving the request my app is rendering twice and also on the client my app is rendering twice:

**Server:**
![image](https://user-images.githubusercontent.com/1508863/29407956-99cf4b8e-8346-11e7-90cd-c494118e14ed.png)

**Client:**
![image](https://user-images.githubusercontent.com/1508863/29407930-7d5f4fee-8346-11e7-8e69-4640e3a45e8f.png)

It only happens when I use `getDataFromTree()` on the server side and on the client side it only occurs when I create my `ApolloClient` using an initial state in the options, in my case like this: `initialState: window.__APOLLO_STATE__`.

There are no other network requests going out from the client, so no queries being enacted etc. which might cause a re-render.

I managed to find the render methods being called in Chrome Devtools:

_You can see the first `App.render` a bit on the left there and the final (much shorter one) is on the right there in the blue bordered block_
![image](https://user-images.githubusercontent.com/1508863/29408513-ca8d44ae-8348-11e7-9be9-8b5313828fe0.png)

Both of those `App.render` methods happen almost directly after a `proxiedMethod` and `GraphQL.render` method.

**How to reproduce the issue:**

On the server (the method that returns all the stuff I place into my HTML response):

```
const apolloClient = new ApolloClient({
    ssrMode: true,
    networkInterface: createNetworkInterface({
      uri: "https://api.graph.cool/simple/v1/cj6dds6fd2t2z0101yktqzgsd",
    }),
  });

console.log("Rendering to React");

const app = wrapAppComponent(App, apolloClient);
await getDataFromTree(app);
const appHtml = renderToString(app);

return { reactHtml: appHtml, reactState: {apollo: apolloClient.getInitialState()} };
```

On the client:

```
const apolloState = window.__APOLLO_STATE__;

const networkInterface = createNetworkInterface({
  uri: "https://api.graph.cool/simple/v1/cj6dds6fd2t2z0101yktqzgsd",
});

const client = new ApolloClient({
  networkInterface,
  initialState: apolloState,
  ssrForceFetchDelay: 100,
});
```

**Version**

* apollo-client@ ?
* react-apollo@1.4.14

**Comment by jbaxleyiii** [comment]
➤ James Baxley commented:

@lostpebble hmm that is no good! Do you have a simple reproduction I can take a look at?

**Comment by jbaxleyiii** [comment]
➤ Paul Myburgh commented:

@jbaxleyiii sure, I took my current project and tried to strip it down as much as possible to create something you can run and check out:

https://github.com/lostpebble/apollo-two-render

Hope it's not too verbose. The main files to look at are ServerRenderReact.tsx and entryProd.tsx

  * for the server side rendering. And then entryHot.tsx for the client side rendering.

**Comment by jbaxleyiii** [comment]
➤ Jihoon Kim commented:

@jbaxleyiii any update on this?

**Comment by jbaxleyiii** [comment]
➤ stale[bot] commented:

This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!

**Comment by jbaxleyiii** [comment]
➤ xabree commented:

I have same issue when using getDataFromTree on server side :(, any Update on this ?

**Comment by jbaxleyiii** [comment]
➤ stale[bot] commented:

This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!

**Comment by jbaxleyiii** [comment]
➤ Maxim Vorontsov commented:

Any updates on this issue?

**Comment by jbaxleyiii** [comment]
➤ stale[bot] commented:

This issue has been automatically labled because it has not had recent activity. If you have not received a response from anyone, please mention the repository maintainer (most likely @jbaxleyiii). It will be closed if no further activity occurs. Thank you for your contributions to React Apollo!

**Comment by jbaxleyiii** [comment]
➤ Marc Alexandre commented:

I can't say for the server rendering code, I've yet to use something like this. But for the client side, it seems logical to have two render. Maybe it's different in typescript from pure javascript, but a graphql query would first send { loading: true, allLinks: undefined } and then send { loading: false, allLinks: ...YOUR_DATA }, which would make 2 renders with your code. And if the "loading" is managed differently in typescript, there is also #1314 that can maybe cause this?

**Comment by lostpebble** [comment]
@jbaxleyiii I'll be able to confirm if this is still an issue for you again soon. Is there a reason you're closing it besides it being a bit stagnant?
