### ISSUE TITLE
clearing out errors when fetchMore is called

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#66]
This fixes #2533. Does this seem like a reasonable amendment?

### Checklist:
* [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
* [ ] Make sure all of the significant new logic is covered by tests
* [x] If this was a change that affects the external API used in GitHunt-React, update GitHunt-React and post a link to the PR in the discussion.

**Comment by jbaxleyiii** [comment]
➤ meteor-bot commented:

@prybalko: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Meteor Contributor Agreement here: https://contribute.meteor.com/

**Comment by jbaxleyiii** [comment]
➤ meteor-bot commented:



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

No CHANGELOG added.
  </td>
    </tr>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

There are library changes, but not tests. That's OK as long as you're refactoring existing code
  </td>
    </tr>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

Please add your name and email to the AUTHORS file (optional)
  </td>
    </tr>

<tr>
      <td>:book:</td>
      <td>

If this was a change that affects the external API, please update the docs and post a link to the PR in the discussion
  </td>
    </tr>
  </tbody>
</table>

<p align="right">
  Generated by :no_entry_sign: [dangerJS](http://github.com/danger/danger-js/)
</p>

**Comment by prybalko** [comment]
@jbaxleyiii ok, done
