### ISSUE TITLE
Stripped @connection directive breaks MockedProvider

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#77]
**Intended outcome:**
I have a test that uses a `MockedProvider` to test a given GraphQL query. This test was running smoothly with `apollo@1.9.1`, but broke once we migrated to `2.0.2`. This is the query we are testing:

```
query WidgetData($id: ID!, $parameter: JSON) {
    widgetData(id: $id, parameter: $parameter) @connection(key: $id)
}
```

**Actual outcome:**
We get this error:
`Error: Network error: No more mocked responses for the query: query WidgetData($id: ID!, $parameter: JSON) {
    widgetData(id: $id, parameter: $parameter)
   }, variables: {"id":"id1"}]`

As it turns out, the problem is that the mocked response is saved under the key 

```
'{"query":"query WidgetData($id: ID!, $parameter: JSON) {\n  widgetData(id: $id, parameter: $parameter) @connection(key: $id)\n}\n","variables":{}}'
```

while it is retrieved under the slightly different key:

```
 '{"query":"query WidgetData($id: ID!, $parameter: JSON) {\n  widgetData(id: $id, parameter: $parameter)\n}\n","variables":{}}'
```

So the `@connection(key: $id)` directive is stripped in the second line, which results in the mock data not being returned correctly.

After lots of debugging, we found the culprit to be this change, where the connect directive is deliberately stripped out:
https://github.com/apollographql/apollo-client/pull/2375/files#diff-fde964badaf130f363bd0d1f7bc71b26R121

**Version**

* apollo-client@2.0.2
* react-apollo@2.0.0

**Comment by brunoreis** [comment]
Please @jbaxleyiii, was there a regression on this one? I'm facing the same behavior using apollo-client 2.4.1 and react-apollo 2.1.11. 

Printing the key generated by "requestToKey in test-utils I can't see the @connection directive in the serialized/printed query. Although the index (this.mockerResponsesByKey) has the @connection there.

**Comment by brunoreis** [comment]
Another info: hacking my mocks with removeConnectionDirectiveFromDocument(query) made it work.
