### ISSUE TITLE
Apollo subscribeToMore on React Native (Android)

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/apollo-link-state#87]
**Intended outcome:**
I followed the docs on Apollo to add subscription to websocket on React Native, i made it work on iOS but nothing happens on Android. I tried on simulator (Genymotion) and on physical device but the subscription doesn't work.

Code of my configuration file:

```javascript
const httpLink = new HttpLink({
  uri: 'https://api.graph.cool/simple/v1/a',
});

const wsLink = new WebSocketLink({
  uri: 'wss://subscriptions.us-west-2.graph.cool/v1/a',
  options: { reconnect: true },
});

const link = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query);
    return kind === 'OperationDefinition' && operation === 'subscription';
  },
  wsLink,
  httpLink,
);

const client = new ApolloClient({
  link,
  cache: new InMemoryCache()
});

export default client;
```

Code of my subscription:

```javascript
this.props.conversation.subscribeToMore({
  document: gql`
    subscription onMessageAdded($author: String!) {
      Message(filter: {
        mutation_in: [CREATED]
        node: {
          from_not: $author
        }
      }) {
        node {
          id
          from
          message
        }
      }
    }
  `,
  variables: {
    author: this.state.author,
  },
  updateQuery: (prev, { subscriptionData }) => {
    if (!subscriptionData['Message']) return prev;

    const newItem = subscriptionData['Message'].node;

    return { ...prev, allMessages: [ ...prev.allMessages, newItem ] };
  }
});
```

**Actual outcome:**
There is no bug on the console, no bugs on android logs, no yellow box, nothing happens. I tried to add some `console.log` to my code to debug the WebSocketLink and my function but everything seems to be ok. I really think it's an Android problem but i can't find more people with the same issue.

**Version**
"apollo-cache-inmemory": "^1.1.0",
"apollo-client": "^2.0.2",
"apollo-link": "^1.0.0",
"apollo-link-http": "^1.1.0",
"apollo-link-ws": "^1.0.0",
"apollo-utilities": "^1.0.1",
"graphql": "^0.11.7",
"graphql-tag": "^2.5.0",
"react": "16.0.0",
"react-apollo": "^2.0.0",
"react-native": "0.50.1"

**Comment by kaiyes** [comment]
@jbaxleyiii  were you able to solve it and if yes how did you do it ?

**Comment by jakequade** [comment]
@jbaxleyiii did you get a solve for this ? I am having the same issue :/
